apiVersion: v1
kind: ConfigMap
metadata:
  # kpt-merge: /rke2-config-setters
  name: rke2-config-setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: apply-setters
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-config-setters'
    description.kpt.dev: Setters for RKE2 config.yaml.d fragments
data:
  cluster-name: bioskop
  node-name: master
  node-kind: server
  cluster-token: bioskop
  node-host-inetaddr: 10.80.56.10
  cluster-id: "0"
  cluster-init: "true"
  pod-network-cidr: 10.56.0.0/16
  service-network-cidr: 10.57.0.0/16
  node-gateway-inetaddr: 10.80.56.1
  cluster-vip-gateway-inetaddr: 10.80.63.1
