apiVersion: v1
kind: ConfigMap
metadata:
  # Generated setter values for RKE2 config.yaml.d templates; kpt-set from Makefile variables
  # should be in synch with rke2.d/catalog/runtime/rke2-config/setters.yaml
  # kpt-merge: /rke2-config-setters
  name: rke2-config-setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: apply-setters
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-config-setters'
    description.kpt.dev: Setters for RKE2 config.yaml.d fragments
data:
  cluster-name: bioskop
  node-name: master
  node-kind: server
  rke2-debug: "true"
  rke2-verbosity: "4"
  cluster-token: bioskop
  node-host-inetaddr: 10.80.0.10
  cluster-id: "0"
  cluster-init: "true"
  pod-network-cidr: 10.42.0.0/16
  service-network-cidr: 10.43.0.0/16
  node-gateway-inetaddr: 10.80.0.1
  cluster-vip-gateway-inetaddr: 10.80.7.1
