apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: tailscale-operator
spec:
  repo: https://pkgs.tailscale.com/helmcharts
  chart: tailscale-operator
  version: ${tailscale-version} # kpt-set: ${tailscale-version}
  targetNamespace: ${tailscale-namespace} # kpt-set: ${tailscale-namespace}
  createNamespace: true
  valuesContent: |-
    operatorConfig:
      hostname: ${cluster-name}-tailscale-operator # kpt-set: ${cluster-name}-tailscale-operator
      debug: true
