apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata: # kpt-merge: /load-balancers
  name: load-balancers
  annotations:
    internal.kpt.dev/upstream-identifier: 'cilium.io|CiliumLoadBalancerIPPool|default|load-balancers'
spec:
  blocks:
    # LoadBalancer pool inside /26 (128/26): usable hosts 129-190
    - cidr: ${cluster-lb-cidr} # kpt-set: ${cluster-lb-cidr}
  serviceSelector:
    matchExpressions:
      # Default pool backs services that do not request a custom pool label
      - key: io.cilium/lb-ipam-pool
        operator: DoesNotExist
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata: # kpt-merge: /lan-load-balancers
  name: lan-load-balancers
  annotations:
    internal.kpt.dev/upstream-identifier: 'cilium.io|CiliumLoadBalancerIPPool|default|lan-load-balancers'
spec:
  blocks:
    # LAN load balancer pool
    - cidr: ${cluster-lan-lb-cidr} # kpt-set: ${cluster-lan-lb-cidr}
  serviceSelector:
    matchLabels:
      io.cilium/loadbalancer-ip-pool: lan-lb
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata: # kpt-merge: /virtual-addresses
  name: virtual-addresses
  annotations:
    internal.kpt.dev/upstream-identifier: 'cilium.io|CiliumLoadBalancerIPPool|default|virtual-addresses'
spec:
  blocks:
    - cidr: ${cluster-vip-cidr} # kpt-set: ${cluster-vip-cidr}
