apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-lan
spec:
  blocks:
  - cidr: ${cluster-lan-lb-cidr} # kpt-set: ${cluster-lan-lb-cidr}
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-pool: home-lan
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: home-lan-policy
spec:
  interfaces:
  - ^lan0$
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-pool: home-lan
