apiVersion: v1
kind: ServiceAccount
metadata:
  name: headscale-client
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headscale-client
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headscale-client
subjects:
- kind: ServiceAccount
  name: headscale-client
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
roleRef:
  kind: ClusterRole
  name: headscale-client
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: headscale-client
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
  labels:
    app: headscale-client
spec:
  selector:
    matchLabels:
      app: headscale-client
  template:
    metadata:
      labels:
        app: headscale-client
    spec:
      serviceAccountName: headscale-client
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: wait-for-headscale
        image: busybox:1.36
        env:
        - name: HEADSCALE_URL
          value: http://headscale.${headscale-namespace}.svc.cluster.local:8080 # kpt-set: http://headscale.${headscale-namespace}.svc.cluster.local:8080
        command:
        - sh
        - -c
        - |
          echo "Waiting for Headscale server..."
          until wget -q -O- "$HEADSCALE_URL/health"; do
            echo "Headscale not ready, retrying in 5s..."
            sleep 5
          done
          echo "Headscale is ready!"
      - name: wait-for-authkey
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for auth key Secret..."
          until [ -f /var/secrets/authkey ]; do
            echo "Auth key not available, retrying in 5s..."
            sleep 5
          done
          echo "Auth key found!"
        volumeMounts:
        - name: authkey
          mountPath: /var/secrets
      containers:
      - name: tailscale
        image: tailscale/tailscale:v1.76.6
        env:
        - name: DARWIN_HOST
          value: ${cluster-name} # kpt-set: ${cluster-name}
        - name: RKE2_CLUSTER_NAME
          value: ${cluster-name} # kpt-set: ${cluster-name}
        - name: RKE2_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: headscale-client-auth
              key: authkey
        - name: TS_STATE_DIR
          value: /var/lib/tailscale
        - name: TS_SOCKET
          value: /var/run/tailscale/tailscaled.sock
        - name: HEADSCALE_URL
          value: http://headscale.${headscale-namespace}.svc.cluster.local:8080 # kpt-set: http://headscale.${headscale-namespace}.svc.cluster.local:8080
        - name: TS_USERSPACE
          value: "true"
        - name: TS_KUBE_SECRET
          value: ""
        command:
        - sh
        - -c
        - |
          set -e
          echo "Starting tailscaled..."
          tailscaled --tun=userspace-networking --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock --verbose=1 &
          TAILSCALED_PID=$$!

          echo "Waiting for tailscaled socket..."
          until [ -S /var/run/tailscale/tailscaled.sock ]; do sleep 1; done

          # Use internal cluster service (HTTP) - client is inside the cluster
          # External clients use https://alcide-headscale via Tailscale operator
          echo "Connecting to Headscale at $$HEADSCALE_URL..."
          tailscale up \
            --login-server=$$HEADSCALE_URL \
            --authkey=file:/var/secrets/authkey \
            --hostname=$${DARWIN_HOST}-$$RKE2_NODENAME \
            --advertise-tags=tag:rke2,tag:alcide \
            --accept-routes \
            --ssh \
            --reset

          echo "Headscale client connected!"
          wait $$TAILSCALED_PID
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - name: dev-net-tun
          mountPath: /dev/net/tun
        - name: tailscale-state
          mountPath: /var/lib/tailscale
        - name: tailscale-socket
          mountPath: /var/run/tailscale
        - name: authkey
          mountPath: /var/secrets
          readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      - name: tailscale-state
        hostPath:
          path: /var/lib/tailscale
          type: DirectoryOrCreate
      - name: tailscale-socket
        emptyDir: {}
      - name: authkey
        secret:
          secretName: headscale-client-auth
          items:
          - key: authkey
            path: authkey
