// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.incus.inputs.NetworkForwardState;
import com.pulumi.incus.outputs.NetworkForwardPort;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type = "incus:index/networkForward:NetworkForward")
public class NetworkForward extends com.pulumi.resources.CustomResource {
  @Export(
      name = "config",
      refs = {Map.class, String.class},
      tree = "[0,1,1]")
  private Output<Map<String, String>> config;

  public Output<Map<String, String>> config() {
    return this.config;
  }

  @Export(
      name = "description",
      refs = {String.class},
      tree = "[0]")
  private Output<String> description;

  public Output<String> description() {
    return this.description;
  }

  @Export(
      name = "listenAddress",
      refs = {String.class},
      tree = "[0]")
  private Output<String> listenAddress;

  public Output<String> listenAddress() {
    return this.listenAddress;
  }

  @Export(
      name = "network",
      refs = {String.class},
      tree = "[0]")
  private Output<String> network;

  public Output<String> network() {
    return this.network;
  }

  @Export(
      name = "ports",
      refs = {List.class, NetworkForwardPort.class},
      tree = "[0,1]")
  private Output<List<NetworkForwardPort>> ports;

  public Output<List<NetworkForwardPort>> ports() {
    return this.ports;
  }

  @Export(
      name = "project",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> project;

  public Output<Optional<String>> project() {
    return Codegen.optional(this.project);
  }

  @Export(
      name = "remote",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> remote;

  public Output<Optional<String>> remote() {
    return Codegen.optional(this.remote);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   */
  public NetworkForward(java.lang.String name) {
    this(name, NetworkForwardArgs.Empty);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   */
  public NetworkForward(java.lang.String name, NetworkForwardArgs args) {
    this(name, args, null);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param options A bag of options that control this resource's behavior.
   */
  public NetworkForward(
      java.lang.String name,
      NetworkForwardArgs args,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/networkForward:NetworkForward",
        name,
        makeArgs(args, options),
        makeResourceOptions(options, Codegen.empty()),
        false,
        Utilities.getPackageRef());
  }

  private NetworkForward(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable NetworkForwardState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/networkForward:NetworkForward",
        name,
        state,
        makeResourceOptions(options, id),
        false,
        Utilities.getPackageRef());
  }

  private static NetworkForwardArgs makeArgs(
      NetworkForwardArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
    if (options != null && options.getUrn().isPresent()) {
      return null;
    }
    return args == null ? NetworkForwardArgs.Empty : args;
  }

  private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(
      @Nullable com.pulumi.resources.CustomResourceOptions options,
      @Nullable Output<java.lang.String> id) {
    var defaultOptions =
        com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
    return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
  }

  /**
   * Get an existing Host resource's state with the given name, ID, and optional extra properties
   * used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state
   * @param options Optional settings to control the behavior of the CustomResource.
   */
  public static NetworkForward get(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable NetworkForwardState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    return new NetworkForward(name, id, state, options);
  }
}
