apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vip-setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: apply-setters
    description.kpt.dev: Sample kube-vip setters; override per cluster copy downstream
data:
  kube-vip-version: v0.8.7
  cluster-node-vip-inetaddr: 10.80.63.10
  cluster-vip-interface: vmnet0
  kube-vip-namespace: kube-vip
