---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNPRENDQWQ2Z0F3SUJBZ0lKQU1BTThlTEQ3WXR6TUFvR0NDcUdTTTQ5QkFNQ01DUXhJakFnQmdOVkJBTU0KR1hKclpUSXRjMlZ5ZG1WeUxXTmhRREUzT0RjNE16UXlNVEF3SGhjTk1qWXdPREk1TURnMU56TXpXaGNOTXpZeApNREUxTURnMU56TXpXakExTVRNd01RWURWUVFERENwbWJHOTRMV052Ym5SeWIyeHNaWEl0ZDJWaWFHOXZheTV5CmEyVXliR0ZpTFhONWMzUmxiUzV6ZG1Nd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTVDIvUkIKTGZaVEovYXJlWEp4T0tuZWVFdVBLeHNwNHdzbDFnVHpvTThvOWN4SUtoRTFjQTdJdEdPZDF1eFJucUljZjVybwpYVVRMT250MTUvbWJibDQrbzRIbk1JSGtNQjBHQTFVZERnUVdCQlFzMTNMRXdHYU9BdWhXL2hla0g1R3hFTkc0CmFEQWZCZ05WSFNNRUdEQVdnQlFVMTdrOVM4SnI2cmNoWUZrQTJaUzgxaW1WS3pBTUJnTlZIUk1CQWY4RUFqQUEKTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRCdkJnTlZIUkVFYURCbQpnaXBtYkc5NExXTnZiblJ5YjJ4c1pYSXRkMlZpYUc5dmF5NXlhMlV5YkdGaUxYTjVjM1JsYlM1emRtT0NPR1pzCmIzZ3RZMjl1ZEhKdmJHeGxjaTEzWldKb2IyOXJMbkpyWlRKc1lXSXRjM2x6ZEdWdExuTjJZeTVqYkhWemRHVnkKTG14dlkyRnNNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJRmg3Yk9oem5xSHh2WnRyMU5mcFpqRGNrUkFZb21sSwpoZFk2a2F3cTRPSkVBaUVBMmNaSkh1N0RERURjcGtwUnh1RmJtMVlVWmNmY2dFbTV2a0pueFA3YkpkOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdYUXUrT2pKYlFxU1hUWHlBZGVaem53NlNyOWozTGlTYjNLVVVoV1hDMXhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFazl2MFFTMzJVeWYycTNseWNUaXAzbmhManlzYktlTUxKZFlFODZEUEtQWE1TQ29STlhBTwp5TFJqbmRic1VaNmlISCthNkYxRXl6cDdkZWY1bTI1ZVBnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: runtime
    io.seedmatic.rke2lab/layer: operators
    io.seedmatic.rke2lab/package: flox-webhook
  name: flox-controller-webhook-tls
  namespace: rke2lab-system
type: kubernetes.io/tls
