---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: helm.cattle.io|HelmChart|kube-system|tailscale-operator
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: tailscale
  name: tailscale-operator
  namespace: kube-system
spec:
  chart: tailscale-operator
  createNamespace: true
  repo: https://pkgs.tailscale.com/helmcharts
  targetNamespace: tailscale-system
  valuesContent: |-
    operatorConfig:
      debug: true
  version: 1.82.0
