{
  description = "RKE2 lab infrastructure and network blueprints";

  inputs = {
    # Use flake-commons as aggregator to stay synchronized with nix-darwin-home
    flake-commons.url = "github:nxmatic/nix-flake-commons/develop";

    # Follow flake-commons versions
    nixpkgs.follows = "flake-commons/nixpkgs";
    flake-utils.follows = "flake-commons/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Build the netplan JAR
        netplanJar = pkgs.stdenv.mkDerivation {
          name = "rke2lab-netplan";
          src = ./.;  # Need full repo for parent POM + BOM resolution

          nativeBuildInputs = [ pkgs.maven pkgs.jdk25 ];

          buildPhase = ''
            # Maven needs a writable HOME for .m2/repository
            mkdir -p $TMPDIR/.m2
            # Install parent POM and BOM first, then build netplan module
            mvn -Dmaven.repo.local=$TMPDIR/.m2/repository \
              install:install-file -Dfile=pom.xml -DpomFile=pom.xml
            mvn -Dmaven.repo.local=$TMPDIR/.m2/repository \
              -f bom/pom.xml install
            mvn -Dmaven.repo.local=$TMPDIR/.m2/repository \
              -f netplan/pom.xml \
              clean package -DskipTests
          '';

          installPhase = ''
            mkdir -p $out/share/java
            cp netplan/target/rke2lab-netplan-*-exec.jar $out/share/java/rke2lab-netplan.jar
          '';
        };

        # Generate network blueprint YAML from Java source of truth
        networkBlueprintYaml = pkgs.stdenv.mkDerivation {
          name = "rke2lab-network-blueprint";

          buildInputs = [ pkgs.jdk25 ];

          dontUnpack = true;

          buildPhase = ''
            # NetplanCli dispatcher routes to yamlExport command
            java -jar ${netplanJar}/share/java/rke2lab-netplan.jar yamlExport > blueprint.yaml
          '';

          installPhase = ''
            mkdir -p $out
            cp blueprint.yaml $out/network-blueprint.yaml
          '';
        };

        # Load network blueprint from YAML (generated by Java source of truth)
        networkBlueprintData = builtins.fromJSON (
          builtins.readFile (
            pkgs.runCommand "blueprint.json" {
              buildInputs = [ pkgs.yq-go ];
            } ''
              ${pkgs.yq-go}/bin/yq -o=json '.' ${networkBlueprintYaml}/network-blueprint.yaml > $out
            ''
          )
        );

        # Export network blueprint with Nix helpers
        networkBlueprint = networkBlueprintData // {
          # Helper to derive MACs for a cluster/node pair
          # Uses the cluster/node ID mappings from the Java-generated YAML
          deriveMacs = cluster: node:
            let
              clusterId = networkBlueprintData.clusters.${cluster};
              nodeId = networkBlueprintData.nodes.${node};
              toHex = n: if n < 16 then "0${pkgs.lib.toLower (pkgs.lib.toHexString n)}" else pkgs.lib.toLower (pkgs.lib.toHexString n);
            in {
              lan = "10:66:6a:4c:${toHex clusterId}:${toHex nodeId}";
              wan = "52:54:00:${toHex clusterId}:${toHex nodeId}:00";
            };
        };

      in {
        packages = {
          inherit netplanJar networkBlueprintYaml;
        };

        # Export the network blueprint for consumption by nix-darwin-home
        lib = {
          inherit networkBlueprint;
          # Also expose the raw YAML for inspection
          networkBlueprintYamlPath = "${networkBlueprintYaml}/network-blueprint.yaml";
        };
      }
    );
}
