---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: cilium.io|CiliumL2AnnouncementPolicy|default|home-lan-policy
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headscale
  name: home-lan-policy
spec:
  interfaces:
    - ^lan0$
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-pool: home-lan
