---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: apps|DaemonSet|${headscale-namespace}|headscale-client
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headscale
  labels:
    app: headscale-client
  name: headscale-client
  namespace: headscale-system
spec:
  selector:
    matchLabels:
      app: headscale-client
  template:
    metadata:
      annotations:
        kpt.dev/package-layer: mesh
        kpt.dev/package-name: headscale
      labels:
        app: headscale-client
    spec:
      containers:
        - command:
            - sh
            - -exc
            - |
              set -ex
              echo "Starting tailscaled..."
              tailscaled --tun=userspace-networking \
                --state=/var/lib/tailscale/tailscaled.state \
                --socket=/var/run/tailscale/tailscaled.sock &
              TAILSCALED_PID=$$!

              echo "Waiting for tailscaled socket..."
              until [ -S /var/run/tailscale/tailscaled.sock ]; do sleep 1; done

              # Use internal cluster service (HTTP) - client is inside the cluster
              # External clients use https://alcide-headscale via Tailscale operator
              echo "Connecting to Headscale at $$HEADSCALE_URL..."
              tailscale up \
                --login-server=$$HEADSCALE_URL \
                --authkey=file:/var/secrets/authkey \
                --hostname=$${DARWIN_HOST}-$$RKE2_NODENAME \
                --advertise-tags=tag:rke2,tag:alcide \
                --accept-routes \
                --ssh \
                --reset

              echo "Headscale client connected!"
              wait $$TAILSCALED_PID
          env:
            - name: DARWIN_HOST
              value: alcide
            - name: RKE2_CLUSTER_NAME
              value: alcide
            - name: RKE2_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  key: authkey
                  name: headscale-client-auth
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
            - name: TS_SOCKET
              value: /var/run/tailscale/tailscaled.sock
            - name: TS_USERSPACE
              value: "true"
            - name: TS_KUBE_SECRET
              value: ""
            - name: HEADSCALE_URL
              value: http://headscale.headscale-system.svc.cluster.local:8080
          image: tailscale/tailscale:v1.76.6
          name: tailscale
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
            privileged: true
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-net-tun
            - mountPath: /var/lib/tailscale
              name: tailscale-state
            - mountPath: /var/run/tailscale
              name: tailscale-socket
            - mountPath: /var/secrets
              name: authkey
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      initContainers:
        - command:
            - sh
            - -exc
            - |
              echo "Waiting for Headscale server..."
              until wget -q -O- "$HEADSCALE_URL/health"; do
                echo "Headscale not ready, retrying in 5s..."
                sleep 5
              done
              echo "Headscale is ready!"
          env:
            - name: HEADSCALE_URL
              value: http://headscale.headscale-system.svc.cluster.local:8080
          image: busybox:1.36
          name: wait-for-headscale
        - command:
            - sh
            - -exc
            - |
              echo "Waiting for auth key Secret..."
              until [ -f /var/secrets/authkey ]; do
                echo "Auth key not available, retrying in 5s..."
                sleep 5
              done
              echo "Auth key found!"
          image: busybox:1.36
          name: wait-for-authkey
          volumeMounts:
            - mountPath: /var/secrets
              name: authkey
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: headscale-client
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - hostPath:
            path: /dev/net/tun
            type: CharDevice
          name: dev-net-tun
        - hostPath:
            path: /var/lib/tailscale
            type: DirectoryOrCreate
          name: tailscale-state
        - emptyDir: {}
          name: tailscale-socket
        - name: authkey
          secret:
            items:
              - key: authkey
                path: authkey
            secretName: headscale-client-auth
