---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|${headscale-namespace}|headscale-client'
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headscale
  name: headscale-client
  namespace: headscale-system
