---
apiVersion: v1
kind: Service
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|${headscale-namespace}|headscale'
    io.cilium/lb-ipam-ips: 192.168.1.65
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headscale
    tailscale.com/expose: "true"
    tailscale.com/hostname: alcide-headscale
  labels:
    app: headscale
    io.cilium/lb-ipam-pool: home-lan
  name: headscale
  namespace: headscale-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: headscale
  type: LoadBalancer
