// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetInstanceResult {
  private String architecture;
  private Map<String, String> config;
  private String description;
  private @Nullable List<GetInstanceDevice> devices;
  private Boolean ephemeral;

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  private String id;

  private String location;
  private String name;
  private List<String> profiles;
  private @Nullable String project;
  private @Nullable String remote;
  private Boolean stateful;
  private String status;
  private String type;

  private GetInstanceResult() {}

  public String architecture() {
    return this.architecture;
  }

  public Map<String, String> config() {
    return this.config;
  }

  public String description() {
    return this.description;
  }

  public List<GetInstanceDevice> devices() {
    return this.devices == null ? List.of() : this.devices;
  }

  public Boolean ephemeral() {
    return this.ephemeral;
  }

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  public String id() {
    return this.id;
  }

  public String location() {
    return this.location;
  }

  public String name() {
    return this.name;
  }

  public List<String> profiles() {
    return this.profiles;
  }

  public Optional<String> project() {
    return Optional.ofNullable(this.project);
  }

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  public Boolean stateful() {
    return this.stateful;
  }

  public String status() {
    return this.status;
  }

  public String type() {
    return this.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetInstanceResult defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private String architecture;
    private Map<String, String> config;
    private String description;
    private @Nullable List<GetInstanceDevice> devices;
    private Boolean ephemeral;
    private String id;
    private String location;
    private String name;
    private List<String> profiles;
    private @Nullable String project;
    private @Nullable String remote;
    private Boolean stateful;
    private String status;
    private String type;

    public Builder() {}

    public Builder(GetInstanceResult defaults) {
      Objects.requireNonNull(defaults);
      this.architecture = defaults.architecture;
      this.config = defaults.config;
      this.description = defaults.description;
      this.devices = defaults.devices;
      this.ephemeral = defaults.ephemeral;
      this.id = defaults.id;
      this.location = defaults.location;
      this.name = defaults.name;
      this.profiles = defaults.profiles;
      this.project = defaults.project;
      this.remote = defaults.remote;
      this.stateful = defaults.stateful;
      this.status = defaults.status;
      this.type = defaults.type;
    }

    @CustomType.Setter
    public Builder architecture(String architecture) {
      if (architecture == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "architecture");
      }
      this.architecture = architecture;
      return this;
    }

    @CustomType.Setter
    public Builder config(Map<String, String> config) {
      if (config == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "config");
      }
      this.config = config;
      return this;
    }

    @CustomType.Setter
    public Builder description(String description) {
      if (description == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "description");
      }
      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder devices(@Nullable List<GetInstanceDevice> devices) {

      this.devices = devices;
      return this;
    }

    public Builder devices(GetInstanceDevice... devices) {
      return devices(List.of(devices));
    }

    @CustomType.Setter
    public Builder ephemeral(Boolean ephemeral) {
      if (ephemeral == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "ephemeral");
      }
      this.ephemeral = ephemeral;
      return this;
    }

    @CustomType.Setter
    public Builder id(String id) {
      if (id == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "id");
      }
      this.id = id;
      return this;
    }

    @CustomType.Setter
    public Builder location(String location) {
      if (location == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "location");
      }
      this.location = location;
      return this;
    }

    @CustomType.Setter
    public Builder name(String name) {
      if (name == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "name");
      }
      this.name = name;
      return this;
    }

    @CustomType.Setter
    public Builder profiles(List<String> profiles) {
      if (profiles == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "profiles");
      }
      this.profiles = profiles;
      return this;
    }

    public Builder profiles(String... profiles) {
      return profiles(List.of(profiles));
    }

    @CustomType.Setter
    public Builder project(@Nullable String project) {

      this.project = project;
      return this;
    }

    @CustomType.Setter
    public Builder remote(@Nullable String remote) {

      this.remote = remote;
      return this;
    }

    @CustomType.Setter
    public Builder stateful(Boolean stateful) {
      if (stateful == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "stateful");
      }
      this.stateful = stateful;
      return this;
    }

    @CustomType.Setter
    public Builder status(String status) {
      if (status == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "status");
      }
      this.status = status;
      return this;
    }

    @CustomType.Setter
    public Builder type(String type) {
      if (type == null) {
        throw new MissingRequiredPropertyException("GetInstanceResult", "type");
      }
      this.type = type;
      return this;
    }

    public GetInstanceResult build() {
      final var _resultValue = new GetInstanceResult();
      _resultValue.architecture = architecture;
      _resultValue.config = config;
      _resultValue.description = description;
      _resultValue.devices = devices;
      _resultValue.ephemeral = ephemeral;
      _resultValue.id = id;
      _resultValue.location = location;
      _resultValue.name = name;
      _resultValue.profiles = profiles;
      _resultValue.project = project;
      _resultValue.remote = remote;
      _resultValue.stateful = stateful;
      _resultValue.status = status;
      _resultValue.type = type;
      return _resultValue;
    }
  }
}
