// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;

@CustomType
public final class GetNetworkForwardPort {
  private String description;
  private String listenPort;
  private String protocol;
  private Boolean snat;
  private String targetAddress;
  private String targetPort;

  private GetNetworkForwardPort() {}

  public String description() {
    return this.description;
  }

  public String listenPort() {
    return this.listenPort;
  }

  public String protocol() {
    return this.protocol;
  }

  public Boolean snat() {
    return this.snat;
  }

  public String targetAddress() {
    return this.targetAddress;
  }

  public String targetPort() {
    return this.targetPort;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetNetworkForwardPort defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private String description;
    private String listenPort;
    private String protocol;
    private Boolean snat;
    private String targetAddress;
    private String targetPort;

    public Builder() {}

    public Builder(GetNetworkForwardPort defaults) {
      Objects.requireNonNull(defaults);
      this.description = defaults.description;
      this.listenPort = defaults.listenPort;
      this.protocol = defaults.protocol;
      this.snat = defaults.snat;
      this.targetAddress = defaults.targetAddress;
      this.targetPort = defaults.targetPort;
    }

    @CustomType.Setter
    public Builder description(String description) {
      if (description == null) {
        throw new MissingRequiredPropertyException("GetNetworkForwardPort", "description");
      }
      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder listenPort(String listenPort) {
      if (listenPort == null) {
        throw new MissingRequiredPropertyException("GetNetworkForwardPort", "listenPort");
      }
      this.listenPort = listenPort;
      return this;
    }

    @CustomType.Setter
    public Builder protocol(String protocol) {
      if (protocol == null) {
        throw new MissingRequiredPropertyException("GetNetworkForwardPort", "protocol");
      }
      this.protocol = protocol;
      return this;
    }

    @CustomType.Setter
    public Builder snat(Boolean snat) {
      if (snat == null) {
        throw new MissingRequiredPropertyException("GetNetworkForwardPort", "snat");
      }
      this.snat = snat;
      return this;
    }

    @CustomType.Setter
    public Builder targetAddress(String targetAddress) {
      if (targetAddress == null) {
        throw new MissingRequiredPropertyException("GetNetworkForwardPort", "targetAddress");
      }
      this.targetAddress = targetAddress;
      return this;
    }

    @CustomType.Setter
    public Builder targetPort(String targetPort) {
      if (targetPort == null) {
        throw new MissingRequiredPropertyException("GetNetworkForwardPort", "targetPort");
      }
      this.targetPort = targetPort;
      return this;
    }

    public GetNetworkForwardPort build() {
      final var _resultValue = new GetNetworkForwardPort();
      _resultValue.description = description;
      _resultValue.listenPort = listenPort;
      _resultValue.protocol = protocol;
      _resultValue.snat = snat;
      _resultValue.targetAddress = targetAddress;
      _resultValue.targetPort = targetPort;
      return _resultValue;
    }
  }
}
