[Unit]
Wants=rke2lab-cluster-manifests.service
Wants=rke2lab-runtime-manifests.service
Wants=rke2lab-storage-manifests.service
Wants=rke2lab-networking-manifests.service
Wants=rke2lab-mesh-manifests.service
Wants=rke2lab-gitops-manifests.service
Wants=rke2lab-tekton-pipelines-manifests.service