apiVersion: v1
kind: Secret
metadata: # kpt-merge: porch-system/porch-git-auth
  name: porch-git-auth
  namespace: porch-system
  labels:
    app.kubernetes.io/replicated: "true"
  annotations:
    replicator.v1.mittwald.de/replicate-from: kube-system/porch-git-auth
    internal.kpt.dev/upstream-identifier: '|Secret|porch-system|porch-git-auth'
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata: # kpt-merge: porch-system/porch-git-ssh
  name: porch-git-ssh
  namespace: porch-system
  labels:
    app.kubernetes.io/replicated: "true"
  annotations:
    replicator.v1.mittwald.de/replicate-from: kube-system/porch-git-ssh
    internal.kpt.dev/upstream-identifier: '|Secret|porch-system|porch-git-ssh'
type: kubernetes.io/ssh-auth
---
apiVersion: v1
kind: Secret
metadata: # kpt-merge: porch-fn-system/porch-git-auth
  name: porch-git-auth
  namespace: porch-fn-system
  labels:
    app.kubernetes.io/replicated: "true"
  annotations:
    replicator.v1.mittwald.de/replicate-from: kube-system/porch-git-auth
    internal.kpt.dev/upstream-identifier: '|Secret|porch-fn-system|porch-git-auth'
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata: # kpt-merge: porch-fn-system/porch-git-ssh
  name: porch-git-ssh
  namespace: porch-fn-system
  labels:
    app.kubernetes.io/replicated: "true"
  annotations:
    replicator.v1.mittwald.de/replicate-from: kube-system/porch-git-ssh
    internal.kpt.dev/upstream-identifier: '|Secret|porch-fn-system|porch-git-ssh'
type: kubernetes.io/ssh-auth
