package io.nxmatic.rke2lab.systemd.cdk8s;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import software.constructs.Construct;

/**
 * A systemd drop-in configuration file.
 *
 * <p>Drop-ins extend or override existing systemd units without modifying the original unit file.
 * They are placed in {@code unit-name.d/drop-in-name.conf}.
 *
 * <p><b>Example</b>: Add hooks to rke2-server.service
 *
 * <pre>{@code
 * SystemdChart chart = new SystemdChart(app, "systemd");
 *
 * new SystemdDropIn(chart, "rke2-server-hooks", "rke2-server.service")
 *     .execStartPre("/srv/host/systemd-scripts.d/rke2lab-server-pre-start.sh")
 *     .execStartPost("/srv/host/systemd-scripts.d/rke2lab-server-post-start.sh")
 *     .wants("rke2lab-manifests.target");
 * }</pre>
 *
 * <p>This generates {@code rke2-server.service.d/rke2lab.conf} with [Service] directives.
 */
public class SystemdDropIn extends Construct {

  private final String targetUnitName;
  private final String dropInFileName;
  private final Map<String, List<String>> serviceSection = new LinkedHashMap<>();
  private final Map<String, List<String>> unitSection = new LinkedHashMap<>();

  /**
   * Creates a drop-in for the specified unit.
   *
   * @param scope parent SystemdChart
   * @param id construct ID (e.g., "rke2-server-hooks")
   * @param targetUnitName the unit to extend (e.g., "rke2-server.service")
   */
  public SystemdDropIn(Construct scope, String id, String targetUnitName) {
    super(scope, id);
    this.targetUnitName = targetUnitName;
    this.dropInFileName = id + ".conf";
    // No self-registration: the SystemdChart discovers its drop-ins by walking the construct
    // tree at synthesis time, so a drop-in is never observed before this constructor finished.
  }

  // === [Unit] Section ===

  /** Adds Wants dependencies (weak requirement). */
  public SystemdDropIn wants(String... units) {
    for (String unit : units) {
      addUnitDirective("Wants", unit);
    }
    return this;
  }

  /** Adds After dependencies (ordering). */
  public SystemdDropIn after(String... units) {
    for (String unit : units) {
      addUnitDirective("After", unit);
    }
    return this;
  }

  /** Adds Requires dependencies (strict requirement). */
  public SystemdDropIn requires(String... units) {
    for (String unit : units) {
      addUnitDirective("Requires", unit);
    }
    return this;
  }

  // === [Service] Section ===

  /** Adds ExecStartPre directive. */
  public SystemdDropIn execStartPre(String command) {
    addServiceDirective("ExecStartPre", command);
    return this;
  }

  /** Adds ExecStartPost directive. */
  public SystemdDropIn execStartPost(String command) {
    addServiceDirective("ExecStartPost", command);
    return this;
  }

  /** Sets Type directive. */
  public SystemdDropIn type(String type) {
    addServiceDirective("Type", type);
    return this;
  }

  // === Helper Methods ===

  private void addUnitDirective(String key, String value) {
    unitSection.computeIfAbsent(key, k -> new ArrayList<>()).add(value);
  }

  private void addServiceDirective(String key, String value) {
    serviceSection.computeIfAbsent(key, k -> new ArrayList<>()).add(value);
  }

  /**
   * Returns the drop-in directory path relative to systemd config root.
   *
   * <p>Example: "rke2-server.service.d"
   */
  public String getDropInDirectory() {
    return targetUnitName + ".d";
  }

  /**
   * Returns the drop-in file name.
   *
   * <p>Example: "rke2lab.conf"
   */
  public String getDropInFileName() {
    return dropInFileName;
  }

  /**
   * Returns the target unit name this drop-in extends.
   *
   * <p>Example: "rke2-server.service"
   */
  public String getTargetUnitName() {
    return targetUnitName;
  }

  /**
   * Writes the drop-in configuration file.
   *
   * @param writer output writer
   * @throws IOException if writing fails
   */
  public void writeDropInFile(Writer writer) throws IOException {
    writer.write("# Generated by rke2lab cdk8s-systemd\n");
    writer.write("# Drop-in for: " + targetUnitName + "\n\n");

    // [Unit] section
    if (!unitSection.isEmpty()) {
      writer.write("[Unit]\n");
      for (Map.Entry<String, List<String>> entry : unitSection.entrySet()) {
        for (String value : entry.getValue()) {
          writer.write(entry.getKey() + "=" + value + "\n");
        }
      }
      writer.write("\n");
    }

    // [Service] section
    if (!serviceSection.isEmpty()) {
      writer.write("[Service]\n");
      for (Map.Entry<String, List<String>> entry : serviceSection.entrySet()) {
        for (String value : entry.getValue()) {
          writer.write(entry.getKey() + "=" + value + "\n");
        }
      }
    }
  }
}
