apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: ${headscale-namespace}/flox-env
  name: flox-env
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
  annotations:
    replicator.v1.mittwald.de/replicate-from: flox-runtime/flox-env
    internal.kpt.dev/upstream-identifier: '|ConfigMap|${headscale-namespace}|flox-env'
data: {}
