---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|porch-system|porch-git-ssh'
    kpt.dev/package-layer: gitops
    kpt.dev/package-name: porch
    replicator.v1.mittwald.de/replicate-from: kube-system/porch-git-ssh
  labels:
    app.kubernetes.io/replicated: "true"
  name: porch-git-ssh
  namespace: porch-system
type: kubernetes.io/ssh-auth
