---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/replicated: "true"
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|porch-system|porch-git-auth'
    kpt.dev/package-layer: gitops
    kpt.dev/package-name: porch
    replicator.v1.mittwald.de/replicate-from: kube-system/porch-git-auth
  name: porch-git-auth
  namespace: porch-system
type: kubernetes.io/basic-auth
