apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata: # kpt-merge: /home-lan
  name: home-lan
  annotations:
    internal.kpt.dev/upstream-identifier: 'cilium.io|CiliumLoadBalancerIPPool|default|home-lan'
spec:
  blocks:
  - cidr: ${cluster-lan-lb-cidr} # kpt-set: ${cluster-lan-lb-cidr}
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-pool: home-lan
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata: # kpt-merge: /home-lan-policy
  name: home-lan-policy
  annotations:
    internal.kpt.dev/upstream-identifier: 'cilium.io|CiliumL2AnnouncementPolicy|default|home-lan-policy'
spec:
  interfaces:
  - ^lan0$
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-pool: home-lan
