// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;

@CustomType
public final class GetNetworkAclEgress {
  private String action;
  private String description;
  private String destination;
  private String destinationPort;
  private String icmpCode;
  private String icmpType;
  private String protocol;
  private String source;
  private String sourcePort;
  private String state;

  private GetNetworkAclEgress() {}

  public String action() {
    return this.action;
  }

  public String description() {
    return this.description;
  }

  public String destination() {
    return this.destination;
  }

  public String destinationPort() {
    return this.destinationPort;
  }

  public String icmpCode() {
    return this.icmpCode;
  }

  public String icmpType() {
    return this.icmpType;
  }

  public String protocol() {
    return this.protocol;
  }

  public String source() {
    return this.source;
  }

  public String sourcePort() {
    return this.sourcePort;
  }

  public String state() {
    return this.state;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetNetworkAclEgress defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private String action;
    private String description;
    private String destination;
    private String destinationPort;
    private String icmpCode;
    private String icmpType;
    private String protocol;
    private String source;
    private String sourcePort;
    private String state;

    public Builder() {}

    public Builder(GetNetworkAclEgress defaults) {
      Objects.requireNonNull(defaults);
      this.action = defaults.action;
      this.description = defaults.description;
      this.destination = defaults.destination;
      this.destinationPort = defaults.destinationPort;
      this.icmpCode = defaults.icmpCode;
      this.icmpType = defaults.icmpType;
      this.protocol = defaults.protocol;
      this.source = defaults.source;
      this.sourcePort = defaults.sourcePort;
      this.state = defaults.state;
    }

    @CustomType.Setter
    public Builder action(String action) {
      if (action == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "action");
      }
      this.action = action;
      return this;
    }

    @CustomType.Setter
    public Builder description(String description) {
      if (description == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "description");
      }
      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder destination(String destination) {
      if (destination == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "destination");
      }
      this.destination = destination;
      return this;
    }

    @CustomType.Setter
    public Builder destinationPort(String destinationPort) {
      if (destinationPort == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "destinationPort");
      }
      this.destinationPort = destinationPort;
      return this;
    }

    @CustomType.Setter
    public Builder icmpCode(String icmpCode) {
      if (icmpCode == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "icmpCode");
      }
      this.icmpCode = icmpCode;
      return this;
    }

    @CustomType.Setter
    public Builder icmpType(String icmpType) {
      if (icmpType == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "icmpType");
      }
      this.icmpType = icmpType;
      return this;
    }

    @CustomType.Setter
    public Builder protocol(String protocol) {
      if (protocol == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "protocol");
      }
      this.protocol = protocol;
      return this;
    }

    @CustomType.Setter
    public Builder source(String source) {
      if (source == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "source");
      }
      this.source = source;
      return this;
    }

    @CustomType.Setter
    public Builder sourcePort(String sourcePort) {
      if (sourcePort == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "sourcePort");
      }
      this.sourcePort = sourcePort;
      return this;
    }

    @CustomType.Setter
    public Builder state(String state) {
      if (state == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclEgress", "state");
      }
      this.state = state;
      return this;
    }

    public GetNetworkAclEgress build() {
      final var _resultValue = new GetNetworkAclEgress();
      _resultValue.action = action;
      _resultValue.description = description;
      _resultValue.destination = destination;
      _resultValue.destinationPort = destinationPort;
      _resultValue.icmpCode = icmpCode;
      _resultValue.icmpType = icmpType;
      _resultValue.protocol = protocol;
      _resultValue.source = source;
      _resultValue.sourcePort = sourcePort;
      _resultValue.state = state;
      return _resultValue;
    }
  }
}
