// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetProfileResult {
  private Map<String, String> config;
  private String description;
  private @Nullable List<GetProfileDevice> devices;

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  private String id;

  private String name;
  private @Nullable String project;
  private @Nullable String remote;

  private GetProfileResult() {}

  public Map<String, String> config() {
    return this.config;
  }

  public String description() {
    return this.description;
  }

  public List<GetProfileDevice> devices() {
    return this.devices == null ? List.of() : this.devices;
  }

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  public String id() {
    return this.id;
  }

  public String name() {
    return this.name;
  }

  public Optional<String> project() {
    return Optional.ofNullable(this.project);
  }

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetProfileResult defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private Map<String, String> config;
    private String description;
    private @Nullable List<GetProfileDevice> devices;
    private String id;
    private String name;
    private @Nullable String project;
    private @Nullable String remote;

    public Builder() {}

    public Builder(GetProfileResult defaults) {
      Objects.requireNonNull(defaults);
      this.config = defaults.config;
      this.description = defaults.description;
      this.devices = defaults.devices;
      this.id = defaults.id;
      this.name = defaults.name;
      this.project = defaults.project;
      this.remote = defaults.remote;
    }

    @CustomType.Setter
    public Builder config(Map<String, String> config) {
      if (config == null) {
        throw new MissingRequiredPropertyException("GetProfileResult", "config");
      }
      this.config = config;
      return this;
    }

    @CustomType.Setter
    public Builder description(String description) {
      if (description == null) {
        throw new MissingRequiredPropertyException("GetProfileResult", "description");
      }
      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder devices(@Nullable List<GetProfileDevice> devices) {

      this.devices = devices;
      return this;
    }

    public Builder devices(GetProfileDevice... devices) {
      return devices(List.of(devices));
    }

    @CustomType.Setter
    public Builder id(String id) {
      if (id == null) {
        throw new MissingRequiredPropertyException("GetProfileResult", "id");
      }
      this.id = id;
      return this;
    }

    @CustomType.Setter
    public Builder name(String name) {
      if (name == null) {
        throw new MissingRequiredPropertyException("GetProfileResult", "name");
      }
      this.name = name;
      return this;
    }

    @CustomType.Setter
    public Builder project(@Nullable String project) {

      this.project = project;
      return this;
    }

    @CustomType.Setter
    public Builder remote(@Nullable String remote) {

      this.remote = remote;
      return this;
    }

    public GetProfileResult build() {
      final var _resultValue = new GetProfileResult();
      _resultValue.config = config;
      _resultValue.description = description;
      _resultValue.devices = devices;
      _resultValue.id = id;
      _resultValue.name = name;
      _resultValue.project = project;
      _resultValue.remote = remote;
      return _resultValue;
    }
  }
}
