// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetStoragePoolResult {
  private Map<String, String> config;
  private String description;
  private String driver;

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  private String id;

  private String name;
  private @Nullable String remote;
  private String status;
  private @Nullable String target;

  private GetStoragePoolResult() {}

  public Map<String, String> config() {
    return this.config;
  }

  public String description() {
    return this.description;
  }

  public String driver() {
    return this.driver;
  }

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  public String id() {
    return this.id;
  }

  public String name() {
    return this.name;
  }

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  public String status() {
    return this.status;
  }

  public Optional<String> target() {
    return Optional.ofNullable(this.target);
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetStoragePoolResult defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private Map<String, String> config;
    private String description;
    private String driver;
    private String id;
    private String name;
    private @Nullable String remote;
    private String status;
    private @Nullable String target;

    public Builder() {}

    public Builder(GetStoragePoolResult defaults) {
      Objects.requireNonNull(defaults);
      this.config = defaults.config;
      this.description = defaults.description;
      this.driver = defaults.driver;
      this.id = defaults.id;
      this.name = defaults.name;
      this.remote = defaults.remote;
      this.status = defaults.status;
      this.target = defaults.target;
    }

    @CustomType.Setter
    public Builder config(Map<String, String> config) {
      if (config == null) {
        throw new MissingRequiredPropertyException("GetStoragePoolResult", "config");
      }
      this.config = config;
      return this;
    }

    @CustomType.Setter
    public Builder description(String description) {
      if (description == null) {
        throw new MissingRequiredPropertyException("GetStoragePoolResult", "description");
      }
      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder driver(String driver) {
      if (driver == null) {
        throw new MissingRequiredPropertyException("GetStoragePoolResult", "driver");
      }
      this.driver = driver;
      return this;
    }

    @CustomType.Setter
    public Builder id(String id) {
      if (id == null) {
        throw new MissingRequiredPropertyException("GetStoragePoolResult", "id");
      }
      this.id = id;
      return this;
    }

    @CustomType.Setter
    public Builder name(String name) {
      if (name == null) {
        throw new MissingRequiredPropertyException("GetStoragePoolResult", "name");
      }
      this.name = name;
      return this;
    }

    @CustomType.Setter
    public Builder remote(@Nullable String remote) {

      this.remote = remote;
      return this;
    }

    @CustomType.Setter
    public Builder status(String status) {
      if (status == null) {
        throw new MissingRequiredPropertyException("GetStoragePoolResult", "status");
      }
      this.status = status;
      return this;
    }

    @CustomType.Setter
    public Builder target(@Nullable String target) {

      this.target = target;
      return this;
    }

    public GetStoragePoolResult build() {
      final var _resultValue = new GetStoragePoolResult();
      _resultValue.config = config;
      _resultValue.description = description;
      _resultValue.driver = driver;
      _resultValue.id = id;
      _resultValue.name = name;
      _resultValue.remote = remote;
      _resultValue.status = status;
      _resultValue.target = target;
      return _resultValue;
    }
  }
}
