[Service]
Environment="PATH=/nix/var/nix/profiles/default/bin:/root/.nix-profile/bin:/var/lib/rancher/rke2/bin:/var/lib/rancher/rke2/agent/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
