---
apiVersion: v1
kind: Service
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|${headscale-namespace}|headplane'
    io.cilium/lb-ipam-ips: 192.168.1.194
    kpt.dev/package-layer: mesh
    kpt.dev/package-name: headplane
  labels:
    app: headplane
    io.cilium/lb-ipam-pool: lan
  name: headplane
  namespace: headscale-system
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: headplane
  type: LoadBalancer
