---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: apps|DaemonSet|${kube-vip-namespace}|kube-vip-ds
    kpt.dev/package-layer: ha
    kpt.dev/package-name: kube-vip
  labels:
    app: kube-vip
  name: kube-vip-ds
  namespace: kube-vip
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      annotations:
        kpt.dev/package-layer: ha
        kpt.dev/package-name: kube-vip
      labels:
        app: kube-vip
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - args:
            - manager
          env:
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_interface
              value: rke2-vip0
            - name: vip_cidr
              value: "32"
            - name: dns_mode
              value: first
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: svc_enable
              value: "false"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "5"
            - name: vip_renewdeadline
              value: "3"
            - name: vip_retryperiod
              value: "1"
            - name: address
              value: 10.80.15.10
          image: ghcr.io/kube-vip/kube-vip:v0.8.7
          imagePullPolicy: Always
          name: kube-vip
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
