// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetClusterMembers {
    private String address;
    private String architecture;
    private String description;
    private String failureDomain;
    private List<String> groups;
    private List<String> roles;
    private String status;

    private GetClusterMembers() {}
    public String address() {
        return this.address;
    }
    public String architecture() {
        return this.architecture;
    }
    public String description() {
        return this.description;
    }
    public String failureDomain() {
        return this.failureDomain;
    }
    public List<String> groups() {
        return this.groups;
    }
    public List<String> roles() {
        return this.roles;
    }
    public String status() {
        return this.status;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetClusterMembers defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String address;
        private String architecture;
        private String description;
        private String failureDomain;
        private List<String> groups;
        private List<String> roles;
        private String status;
        public Builder() {}
        public Builder(GetClusterMembers defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.address = defaults.address;
    	      this.architecture = defaults.architecture;
    	      this.description = defaults.description;
    	      this.failureDomain = defaults.failureDomain;
    	      this.groups = defaults.groups;
    	      this.roles = defaults.roles;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder address(String address) {
            if (address == null) {
              throw new MissingRequiredPropertyException("GetClusterMembers", "address");
            }
            this.address = address;
            return this;
        }
        @CustomType.Setter
        public Builder architecture(String architecture) {
            if (architecture == null) {
              throw new MissingRequiredPropertyException("GetClusterMembers", "architecture");
            }
            this.architecture = architecture;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetClusterMembers", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder failureDomain(String failureDomain) {
            if (failureDomain == null) {
              throw new MissingRequiredPropertyException("GetClusterMembers", "failureDomain");
            }
            this.failureDomain = failureDomain;
            return this;
        }
        @CustomType.Setter
        public Builder groups(List<String> groups) {
            if (groups == null) {
              throw new MissingRequiredPropertyException("GetClusterMembers", "groups");
            }
            this.groups = groups;
            return this;
        }
        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }
        @CustomType.Setter
        public Builder roles(List<String> roles) {
            if (roles == null) {
              throw new MissingRequiredPropertyException("GetClusterMembers", "roles");
            }
            this.roles = roles;
            return this;
        }
        public Builder roles(String... roles) {
            return roles(List.of(roles));
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("GetClusterMembers", "status");
            }
            this.status = status;
            return this;
        }
        public GetClusterMembers build() {
            final var _resultValue = new GetClusterMembers();
            _resultValue.address = address;
            _resultValue.architecture = architecture;
            _resultValue.description = description;
            _resultValue.failureDomain = failureDomain;
            _resultValue.groups = groups;
            _resultValue.roles = roles;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
