// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetNetworkPeerResult {
    private Map<String,String> config;
    private String description;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String name;
    private String network;
    private @Nullable String project;
    private @Nullable String remote;
    private String status;
    private String targetIntegration;
    private String targetNetwork;
    private String targetProject;
    private String type;

    private GetNetworkPeerResult() {}
    public Map<String,String> config() {
        return this.config;
    }
    public String description() {
        return this.description;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public String network() {
        return this.network;
    }
    public Optional<String> project() {
        return Optional.ofNullable(this.project);
    }
    public Optional<String> remote() {
        return Optional.ofNullable(this.remote);
    }
    public String status() {
        return this.status;
    }
    public String targetIntegration() {
        return this.targetIntegration;
    }
    public String targetNetwork() {
        return this.targetNetwork;
    }
    public String targetProject() {
        return this.targetProject;
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkPeerResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Map<String,String> config;
        private String description;
        private String id;
        private String name;
        private String network;
        private @Nullable String project;
        private @Nullable String remote;
        private String status;
        private String targetIntegration;
        private String targetNetwork;
        private String targetProject;
        private String type;
        public Builder() {}
        public Builder(GetNetworkPeerResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.config = defaults.config;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.network = defaults.network;
    	      this.project = defaults.project;
    	      this.remote = defaults.remote;
    	      this.status = defaults.status;
    	      this.targetIntegration = defaults.targetIntegration;
    	      this.targetNetwork = defaults.targetNetwork;
    	      this.targetProject = defaults.targetProject;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder config(Map<String,String> config) {
            if (config == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "config");
            }
            this.config = config;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder network(String network) {
            if (network == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "network");
            }
            this.network = network;
            return this;
        }
        @CustomType.Setter
        public Builder project(@Nullable String project) {

            this.project = project;
            return this;
        }
        @CustomType.Setter
        public Builder remote(@Nullable String remote) {

            this.remote = remote;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "status");
            }
            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder targetIntegration(String targetIntegration) {
            if (targetIntegration == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "targetIntegration");
            }
            this.targetIntegration = targetIntegration;
            return this;
        }
        @CustomType.Setter
        public Builder targetNetwork(String targetNetwork) {
            if (targetNetwork == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "targetNetwork");
            }
            this.targetNetwork = targetNetwork;
            return this;
        }
        @CustomType.Setter
        public Builder targetProject(String targetProject) {
            if (targetProject == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "targetProject");
            }
            this.targetProject = targetProject;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetNetworkPeerResult", "type");
            }
            this.type = type;
            return this;
        }
        public GetNetworkPeerResult build() {
            final var _resultValue = new GetNetworkPeerResult();
            _resultValue.config = config;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.network = network;
            _resultValue.project = project;
            _resultValue.remote = remote;
            _resultValue.status = status;
            _resultValue.targetIntegration = targetIntegration;
            _resultValue.targetNetwork = targetNetwork;
            _resultValue.targetProject = targetProject;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
