// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNetworkLoadBalancerPort {
    private String description;
    private String listenPort;
    private String protocol;
    private List<String> targetBackends;

    private GetNetworkLoadBalancerPort() {}
    public String description() {
        return this.description;
    }
    public String listenPort() {
        return this.listenPort;
    }
    public String protocol() {
        return this.protocol;
    }
    public List<String> targetBackends() {
        return this.targetBackends;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkLoadBalancerPort defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String listenPort;
        private String protocol;
        private List<String> targetBackends;
        public Builder() {}
        public Builder(GetNetworkLoadBalancerPort defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.listenPort = defaults.listenPort;
    	      this.protocol = defaults.protocol;
    	      this.targetBackends = defaults.targetBackends;
        }

        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetNetworkLoadBalancerPort", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder listenPort(String listenPort) {
            if (listenPort == null) {
              throw new MissingRequiredPropertyException("GetNetworkLoadBalancerPort", "listenPort");
            }
            this.listenPort = listenPort;
            return this;
        }
        @CustomType.Setter
        public Builder protocol(String protocol) {
            if (protocol == null) {
              throw new MissingRequiredPropertyException("GetNetworkLoadBalancerPort", "protocol");
            }
            this.protocol = protocol;
            return this;
        }
        @CustomType.Setter
        public Builder targetBackends(List<String> targetBackends) {
            if (targetBackends == null) {
              throw new MissingRequiredPropertyException("GetNetworkLoadBalancerPort", "targetBackends");
            }
            this.targetBackends = targetBackends;
            return this;
        }
        public Builder targetBackends(String... targetBackends) {
            return targetBackends(List.of(targetBackends));
        }
        public GetNetworkLoadBalancerPort build() {
            final var _resultValue = new GetNetworkLoadBalancerPort();
            _resultValue.description = description;
            _resultValue.listenPort = listenPort;
            _resultValue.protocol = protocol;
            _resultValue.targetBackends = targetBackends;
            return _resultValue;
        }
    }
}
