// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.incus.outputs.GetNetworkForwardPort;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetNetworkForwardResult {
    private Map<String,String> config;
    private String description;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String listenAddress;
    private String location;
    private String network;
    private List<GetNetworkForwardPort> ports;
    private @Nullable String project;
    private @Nullable String remote;
    private @Nullable String target;

    private GetNetworkForwardResult() {}
    public Map<String,String> config() {
        return this.config;
    }
    public String description() {
        return this.description;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String listenAddress() {
        return this.listenAddress;
    }
    public String location() {
        return this.location;
    }
    public String network() {
        return this.network;
    }
    public List<GetNetworkForwardPort> ports() {
        return this.ports;
    }
    public Optional<String> project() {
        return Optional.ofNullable(this.project);
    }
    public Optional<String> remote() {
        return Optional.ofNullable(this.remote);
    }
    public Optional<String> target() {
        return Optional.ofNullable(this.target);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkForwardResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Map<String,String> config;
        private String description;
        private String id;
        private String listenAddress;
        private String location;
        private String network;
        private List<GetNetworkForwardPort> ports;
        private @Nullable String project;
        private @Nullable String remote;
        private @Nullable String target;
        public Builder() {}
        public Builder(GetNetworkForwardResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.config = defaults.config;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.listenAddress = defaults.listenAddress;
    	      this.location = defaults.location;
    	      this.network = defaults.network;
    	      this.ports = defaults.ports;
    	      this.project = defaults.project;
    	      this.remote = defaults.remote;
    	      this.target = defaults.target;
        }

        @CustomType.Setter
        public Builder config(Map<String,String> config) {
            if (config == null) {
              throw new MissingRequiredPropertyException("GetNetworkForwardResult", "config");
            }
            this.config = config;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetNetworkForwardResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNetworkForwardResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder listenAddress(String listenAddress) {
            if (listenAddress == null) {
              throw new MissingRequiredPropertyException("GetNetworkForwardResult", "listenAddress");
            }
            this.listenAddress = listenAddress;
            return this;
        }
        @CustomType.Setter
        public Builder location(String location) {
            if (location == null) {
              throw new MissingRequiredPropertyException("GetNetworkForwardResult", "location");
            }
            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder network(String network) {
            if (network == null) {
              throw new MissingRequiredPropertyException("GetNetworkForwardResult", "network");
            }
            this.network = network;
            return this;
        }
        @CustomType.Setter
        public Builder ports(List<GetNetworkForwardPort> ports) {
            if (ports == null) {
              throw new MissingRequiredPropertyException("GetNetworkForwardResult", "ports");
            }
            this.ports = ports;
            return this;
        }
        public Builder ports(GetNetworkForwardPort... ports) {
            return ports(List.of(ports));
        }
        @CustomType.Setter
        public Builder project(@Nullable String project) {

            this.project = project;
            return this;
        }
        @CustomType.Setter
        public Builder remote(@Nullable String remote) {

            this.remote = remote;
            return this;
        }
        @CustomType.Setter
        public Builder target(@Nullable String target) {

            this.target = target;
            return this;
        }
        public GetNetworkForwardResult build() {
            final var _resultValue = new GetNetworkForwardResult();
            _resultValue.config = config;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.listenAddress = listenAddress;
            _resultValue.location = location;
            _resultValue.network = network;
            _resultValue.ports = ports;
            _resultValue.project = project;
            _resultValue.remote = remote;
            _resultValue.target = target;
            return _resultValue;
        }
    }
}
