// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetStorageBucketResult {
    private Map<String,String> config;
    private String description;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String location;
    private String name;
    private @Nullable String project;
    private @Nullable String remote;
    private String s3Url;
    private String storagePool;
    private @Nullable String target;

    private GetStorageBucketResult() {}
    public Map<String,String> config() {
        return this.config;
    }
    public String description() {
        return this.description;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String location() {
        return this.location;
    }
    public String name() {
        return this.name;
    }
    public Optional<String> project() {
        return Optional.ofNullable(this.project);
    }
    public Optional<String> remote() {
        return Optional.ofNullable(this.remote);
    }
    public String s3Url() {
        return this.s3Url;
    }
    public String storagePool() {
        return this.storagePool;
    }
    public Optional<String> target() {
        return Optional.ofNullable(this.target);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetStorageBucketResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Map<String,String> config;
        private String description;
        private String id;
        private String location;
        private String name;
        private @Nullable String project;
        private @Nullable String remote;
        private String s3Url;
        private String storagePool;
        private @Nullable String target;
        public Builder() {}
        public Builder(GetStorageBucketResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.config = defaults.config;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.location = defaults.location;
    	      this.name = defaults.name;
    	      this.project = defaults.project;
    	      this.remote = defaults.remote;
    	      this.s3Url = defaults.s3Url;
    	      this.storagePool = defaults.storagePool;
    	      this.target = defaults.target;
        }

        @CustomType.Setter
        public Builder config(Map<String,String> config) {
            if (config == null) {
              throw new MissingRequiredPropertyException("GetStorageBucketResult", "config");
            }
            this.config = config;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetStorageBucketResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetStorageBucketResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder location(String location) {
            if (location == null) {
              throw new MissingRequiredPropertyException("GetStorageBucketResult", "location");
            }
            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetStorageBucketResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder project(@Nullable String project) {

            this.project = project;
            return this;
        }
        @CustomType.Setter
        public Builder remote(@Nullable String remote) {

            this.remote = remote;
            return this;
        }
        @CustomType.Setter
        public Builder s3Url(String s3Url) {
            if (s3Url == null) {
              throw new MissingRequiredPropertyException("GetStorageBucketResult", "s3Url");
            }
            this.s3Url = s3Url;
            return this;
        }
        @CustomType.Setter
        public Builder storagePool(String storagePool) {
            if (storagePool == null) {
              throw new MissingRequiredPropertyException("GetStorageBucketResult", "storagePool");
            }
            this.storagePool = storagePool;
            return this;
        }
        @CustomType.Setter
        public Builder target(@Nullable String target) {

            this.target = target;
            return this;
        }
        public GetStorageBucketResult build() {
            final var _resultValue = new GetStorageBucketResult();
            _resultValue.config = config;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.location = location;
            _resultValue.name = name;
            _resultValue.project = project;
            _resultValue.remote = remote;
            _resultValue.s3Url = s3Url;
            _resultValue.storagePool = storagePool;
            _resultValue.target = target;
            return _resultValue;
        }
    }
}
