// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetStorageVolumeResult {
  private Map<String, String> config;
  private String contentType;
  private String description;

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  private String id;

  private String location;
  private String name;
  private @Nullable String project;
  private @Nullable String remote;
  private String storagePool;
  private @Nullable String target;
  private String type;

  private GetStorageVolumeResult() {}

  public Map<String, String> config() {
    return this.config;
  }

  public String contentType() {
    return this.contentType;
  }

  public String description() {
    return this.description;
  }

  /**
   * @return The provider-assigned unique ID for this managed resource.
   */
  public String id() {
    return this.id;
  }

  public String location() {
    return this.location;
  }

  public String name() {
    return this.name;
  }

  public Optional<String> project() {
    return Optional.ofNullable(this.project);
  }

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  public String storagePool() {
    return this.storagePool;
  }

  public Optional<String> target() {
    return Optional.ofNullable(this.target);
  }

  public String type() {
    return this.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetStorageVolumeResult defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private Map<String, String> config;
    private String contentType;
    private String description;
    private String id;
    private String location;
    private String name;
    private @Nullable String project;
    private @Nullable String remote;
    private String storagePool;
    private @Nullable String target;
    private String type;

    public Builder() {}

    public Builder(GetStorageVolumeResult defaults) {
      Objects.requireNonNull(defaults);
      this.config = defaults.config;
      this.contentType = defaults.contentType;
      this.description = defaults.description;
      this.id = defaults.id;
      this.location = defaults.location;
      this.name = defaults.name;
      this.project = defaults.project;
      this.remote = defaults.remote;
      this.storagePool = defaults.storagePool;
      this.target = defaults.target;
      this.type = defaults.type;
    }

    @CustomType.Setter
    public Builder config(Map<String, String> config) {
      if (config == null) {
        throw new MissingRequiredPropertyException("GetStorageVolumeResult", "config");
      }
      this.config = config;
      return this;
    }

    @CustomType.Setter
    public Builder contentType(String contentType) {
      if (contentType == null) {
        throw new MissingRequiredPropertyException("GetStorageVolumeResult", "contentType");
      }
      this.contentType = contentType;
      return this;
    }

    @CustomType.Setter
    public Builder description(String description) {
      if (description == null) {
        throw new MissingRequiredPropertyException("GetStorageVolumeResult", "description");
      }
      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder id(String id) {
      if (id == null) {
        throw new MissingRequiredPropertyException("GetStorageVolumeResult", "id");
      }
      this.id = id;
      return this;
    }

    @CustomType.Setter
    public Builder location(String location) {
      if (location == null) {
        throw new MissingRequiredPropertyException("GetStorageVolumeResult", "location");
      }
      this.location = location;
      return this;
    }

    @CustomType.Setter
    public Builder name(String name) {
      if (name == null) {
        throw new MissingRequiredPropertyException("GetStorageVolumeResult", "name");
      }
      this.name = name;
      return this;
    }

    @CustomType.Setter
    public Builder project(@Nullable String project) {

      this.project = project;
      return this;
    }

    @CustomType.Setter
    public Builder remote(@Nullable String remote) {

      this.remote = remote;
      return this;
    }

    @CustomType.Setter
    public Builder storagePool(String storagePool) {
      if (storagePool == null) {
        throw new MissingRequiredPropertyException("GetStorageVolumeResult", "storagePool");
      }
      this.storagePool = storagePool;
      return this;
    }

    @CustomType.Setter
    public Builder target(@Nullable String target) {

      this.target = target;
      return this;
    }

    @CustomType.Setter
    public Builder type(String type) {
      if (type == null) {
        throw new MissingRequiredPropertyException("GetStorageVolumeResult", "type");
      }
      this.type = type;
      return this;
    }

    public GetStorageVolumeResult build() {
      final var _resultValue = new GetStorageVolumeResult();
      _resultValue.config = config;
      _resultValue.contentType = contentType;
      _resultValue.description = description;
      _resultValue.id = id;
      _resultValue.location = location;
      _resultValue.name = name;
      _resultValue.project = project;
      _resultValue.remote = remote;
      _resultValue.storagePool = storagePool;
      _resultValue.target = target;
      _resultValue.type = type;
      return _resultValue;
    }
  }
}
