// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ImageSourceInstance {
    private String name;
    private @Nullable String snapshot;

    private ImageSourceInstance() {}
    public String name() {
        return this.name;
    }
    public Optional<String> snapshot() {
        return Optional.ofNullable(this.snapshot);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ImageSourceInstance defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private @Nullable String snapshot;
        public Builder() {}
        public Builder(ImageSourceInstance defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.snapshot = defaults.snapshot;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("ImageSourceInstance", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder snapshot(@Nullable String snapshot) {

            this.snapshot = snapshot;
            return this;
        }
        public ImageSourceInstance build() {
            final var _resultValue = new ImageSourceInstance();
            _resultValue.name = name;
            _resultValue.snapshot = snapshot;
            return _resultValue;
        }
    }
}
