// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkLbBackend {
    /**
     * @return LB backend description
     * 
     */
    private @Nullable String description;
    /**
     * @return LB backend name
     * 
     */
    private String name;
    /**
     * @return LB backend target address
     * 
     */
    private String targetAddress;
    /**
     * @return LB backend target port
     * 
     */
    private @Nullable String targetPort;

    private NetworkLbBackend() {}
    /**
     * @return LB backend description
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return LB backend name
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return LB backend target address
     * 
     */
    public String targetAddress() {
        return this.targetAddress;
    }
    /**
     * @return LB backend target port
     * 
     */
    public Optional<String> targetPort() {
        return Optional.ofNullable(this.targetPort);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkLbBackend defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String description;
        private String name;
        private String targetAddress;
        private @Nullable String targetPort;
        public Builder() {}
        public Builder(NetworkLbBackend defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.name = defaults.name;
    	      this.targetAddress = defaults.targetAddress;
    	      this.targetPort = defaults.targetPort;
        }

        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("NetworkLbBackend", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder targetAddress(String targetAddress) {
            if (targetAddress == null) {
              throw new MissingRequiredPropertyException("NetworkLbBackend", "targetAddress");
            }
            this.targetAddress = targetAddress;
            return this;
        }
        @CustomType.Setter
        public Builder targetPort(@Nullable String targetPort) {

            this.targetPort = targetPort;
            return this;
        }
        public NetworkLbBackend build() {
            final var _resultValue = new NetworkLbBackend();
            _resultValue.description = description;
            _resultValue.name = name;
            _resultValue.targetAddress = targetAddress;
            _resultValue.targetPort = targetPort;
            return _resultValue;
        }
    }
}
