// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkLbPort {
  /**
   * @return Port description
   */
  private @Nullable String description;

  /**
   * @return Port to listen to
   */
  private String listenPort;

  /**
   * @return Port protocol
   */
  private @Nullable String protocol;

  /**
   * @return List of target LB backends
   */
  private List<String> targetBackends;

  private NetworkLbPort() {}

  /**
   * @return Port description
   */
  public Optional<String> description() {
    return Optional.ofNullable(this.description);
  }

  /**
   * @return Port to listen to
   */
  public String listenPort() {
    return this.listenPort;
  }

  /**
   * @return Port protocol
   */
  public Optional<String> protocol() {
    return Optional.ofNullable(this.protocol);
  }

  /**
   * @return List of target LB backends
   */
  public List<String> targetBackends() {
    return this.targetBackends;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(NetworkLbPort defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private @Nullable String description;
    private String listenPort;
    private @Nullable String protocol;
    private List<String> targetBackends;

    public Builder() {}

    public Builder(NetworkLbPort defaults) {
      Objects.requireNonNull(defaults);
      this.description = defaults.description;
      this.listenPort = defaults.listenPort;
      this.protocol = defaults.protocol;
      this.targetBackends = defaults.targetBackends;
    }

    @CustomType.Setter
    public Builder description(@Nullable String description) {

      this.description = description;
      return this;
    }

    @CustomType.Setter
    public Builder listenPort(String listenPort) {
      if (listenPort == null) {
        throw new MissingRequiredPropertyException("NetworkLbPort", "listenPort");
      }
      this.listenPort = listenPort;
      return this;
    }

    @CustomType.Setter
    public Builder protocol(@Nullable String protocol) {

      this.protocol = protocol;
      return this;
    }

    @CustomType.Setter
    public Builder targetBackends(List<String> targetBackends) {
      if (targetBackends == null) {
        throw new MissingRequiredPropertyException("NetworkLbPort", "targetBackends");
      }
      this.targetBackends = targetBackends;
      return this;
    }

    public Builder targetBackends(String... targetBackends) {
      return targetBackends(List.of(targetBackends));
    }

    public NetworkLbPort build() {
      final var _resultValue = new NetworkLbPort();
      _resultValue.description = description;
      _resultValue.listenPort = listenPort;
      _resultValue.protocol = protocol;
      _resultValue.targetBackends = targetBackends;
      return _resultValue;
    }
  }
}
