// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkZoneRecordEntry {
  /**
   * @return Record entry TTL
   */
  private @Nullable Double ttl;

  /**
   * @return Record entry type
   */
  private String type;

  /**
   * @return Record entry value
   */
  private String value;

  private NetworkZoneRecordEntry() {}

  /**
   * @return Record entry TTL
   */
  public Optional<Double> ttl() {
    return Optional.ofNullable(this.ttl);
  }

  /**
   * @return Record entry type
   */
  public String type() {
    return this.type;
  }

  /**
   * @return Record entry value
   */
  public String value() {
    return this.value;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(NetworkZoneRecordEntry defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private @Nullable Double ttl;
    private String type;
    private String value;

    public Builder() {}

    public Builder(NetworkZoneRecordEntry defaults) {
      Objects.requireNonNull(defaults);
      this.ttl = defaults.ttl;
      this.type = defaults.type;
      this.value = defaults.value;
    }

    @CustomType.Setter
    public Builder ttl(@Nullable Double ttl) {

      this.ttl = ttl;
      return this;
    }

    @CustomType.Setter
    public Builder type(String type) {
      if (type == null) {
        throw new MissingRequiredPropertyException("NetworkZoneRecordEntry", "type");
      }
      this.type = type;
      return this;
    }

    @CustomType.Setter
    public Builder value(String value) {
      if (value == null) {
        throw new MissingRequiredPropertyException("NetworkZoneRecordEntry", "value");
      }
      this.value = value;
      return this;
    }

    public NetworkZoneRecordEntry build() {
      final var _resultValue = new NetworkZoneRecordEntry();
      _resultValue.ttl = ttl;
      _resultValue.type = type;
      _resultValue.value = value;
      return _resultValue;
    }
  }
}
