// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkForwardPort {
    /**
     * @return Port description
     * 
     */
    private @Nullable String description;
    /**
     * @return Listen port to forward
     * 
     */
    private String listenPort;
    /**
     * @return Port protocol
     * 
     */
    private @Nullable String protocol;
    /**
     * @return Target address to forward listen port to
     * 
     */
    private String targetAddress;
    /**
     * @return Target port to forward listen port to
     * 
     */
    private String targetPort;

    private NetworkForwardPort() {}
    /**
     * @return Port description
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return Listen port to forward
     * 
     */
    public String listenPort() {
        return this.listenPort;
    }
    /**
     * @return Port protocol
     * 
     */
    public Optional<String> protocol() {
        return Optional.ofNullable(this.protocol);
    }
    /**
     * @return Target address to forward listen port to
     * 
     */
    public String targetAddress() {
        return this.targetAddress;
    }
    /**
     * @return Target port to forward listen port to
     * 
     */
    public String targetPort() {
        return this.targetPort;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkForwardPort defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String description;
        private String listenPort;
        private @Nullable String protocol;
        private String targetAddress;
        private String targetPort;
        public Builder() {}
        public Builder(NetworkForwardPort defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.listenPort = defaults.listenPort;
    	      this.protocol = defaults.protocol;
    	      this.targetAddress = defaults.targetAddress;
    	      this.targetPort = defaults.targetPort;
        }

        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder listenPort(String listenPort) {
            if (listenPort == null) {
              throw new MissingRequiredPropertyException("NetworkForwardPort", "listenPort");
            }
            this.listenPort = listenPort;
            return this;
        }
        @CustomType.Setter
        public Builder protocol(@Nullable String protocol) {

            this.protocol = protocol;
            return this;
        }
        @CustomType.Setter
        public Builder targetAddress(String targetAddress) {
            if (targetAddress == null) {
              throw new MissingRequiredPropertyException("NetworkForwardPort", "targetAddress");
            }
            this.targetAddress = targetAddress;
            return this;
        }
        @CustomType.Setter
        public Builder targetPort(String targetPort) {
            if (targetPort == null) {
              throw new MissingRequiredPropertyException("NetworkForwardPort", "targetPort");
            }
            this.targetPort = targetPort;
            return this;
        }
        public NetworkForwardPort build() {
            final var _resultValue = new NetworkForwardPort();
            _resultValue.description = description;
            _resultValue.listenPort = listenPort;
            _resultValue.protocol = protocol;
            _resultValue.targetAddress = targetAddress;
            _resultValue.targetPort = targetPort;
            return _resultValue;
        }
    }
}
