// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class ProfileDevice {
  /**
   * @return Device name
   */
  private String name;

  /**
   * @return Device properties
   */
  private Map<String, String> properties;

  /**
   * @return Device type
   */
  private String type;

  private ProfileDevice() {}

  /**
   * @return Device name
   */
  public String name() {
    return this.name;
  }

  /**
   * @return Device properties
   */
  public Map<String, String> properties() {
    return this.properties;
  }

  /**
   * @return Device type
   */
  public String type() {
    return this.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(ProfileDevice defaults) {
    return new Builder(defaults);
  }

  @CustomType.Builder
  public static final class Builder {
    private String name;
    private Map<String, String> properties;
    private String type;

    public Builder() {}

    public Builder(ProfileDevice defaults) {
      Objects.requireNonNull(defaults);
      this.name = defaults.name;
      this.properties = defaults.properties;
      this.type = defaults.type;
    }

    @CustomType.Setter
    public Builder name(String name) {
      if (name == null) {
        throw new MissingRequiredPropertyException("ProfileDevice", "name");
      }
      this.name = name;
      return this;
    }

    @CustomType.Setter
    public Builder properties(Map<String, String> properties) {
      if (properties == null) {
        throw new MissingRequiredPropertyException("ProfileDevice", "properties");
      }
      this.properties = properties;
      return this;
    }

    @CustomType.Setter
    public Builder type(String type) {
      if (type == null) {
        throw new MissingRequiredPropertyException("ProfileDevice", "type");
      }
      this.type = type;
      return this;
    }

    public ProfileDevice build() {
      final var _resultValue = new ProfileDevice();
      _resultValue.name = name;
      _resultValue.properties = properties;
      _resultValue.type = type;
      return _resultValue;
    }
  }
}
