---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mesh-funnel-cert-restore-operators.yml
- mesh-funnel-cert-restore-workloads.yml
- mesh-funnel-state-operators.yml
- mesh-funnel-state-workloads.yml
- mesh-headplane.yml
- mesh-headscale.yml
- mesh-system-namespace-foundation.yml
- mesh-system-namespace-workloads.yml
- mesh-tailscale-operators.yml
- mesh-tailscale-workloads.yml
