apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /debug
  name: debug.yaml
  annotations:
    description.kpt.dev: Enable RKE2 debug logging for manifest watcher
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|debug'
data:
  debug: "${rke2-debug}" # kpt-set: ${rke2-debug}
  v: "${rke2-verbosity}" # kpt-set: ${rke2-verbosity}
