// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class GetInstancePlainArgs extends com.pulumi.resources.InvokeArgs {

  public static final GetInstancePlainArgs Empty = new GetInstancePlainArgs();

  @Import(name = "architecture")
  private @Nullable String architecture;

  public Optional<String> architecture() {
    return Optional.ofNullable(this.architecture);
  }

  @Import(name = "description")
  private @Nullable String description;

  public Optional<String> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "devices")
  private @Nullable List<GetInstanceDevice> devices;

  public Optional<List<GetInstanceDevice>> devices() {
    return Optional.ofNullable(this.devices);
  }

  @Import(name = "ephemeral")
  private @Nullable Boolean ephemeral;

  public Optional<Boolean> ephemeral() {
    return Optional.ofNullable(this.ephemeral);
  }

  @Import(name = "location")
  private @Nullable String location;

  public Optional<String> location() {
    return Optional.ofNullable(this.location);
  }

  @Import(name = "name", required = true)
  private String name;

  public String name() {
    return this.name;
  }

  @Import(name = "profiles")
  private @Nullable List<String> profiles;

  public Optional<List<String>> profiles() {
    return Optional.ofNullable(this.profiles);
  }

  @Import(name = "project")
  private @Nullable String project;

  public Optional<String> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable String remote;

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "stateful")
  private @Nullable Boolean stateful;

  public Optional<Boolean> stateful() {
    return Optional.ofNullable(this.stateful);
  }

  @Import(name = "status")
  private @Nullable String status;

  public Optional<String> status() {
    return Optional.ofNullable(this.status);
  }

  @Import(name = "type")
  private @Nullable String type;

  public Optional<String> type() {
    return Optional.ofNullable(this.type);
  }

  private GetInstancePlainArgs() {}

  private GetInstancePlainArgs(GetInstancePlainArgs $) {
    this.architecture = $.architecture;
    this.description = $.description;
    this.devices = $.devices;
    this.ephemeral = $.ephemeral;
    this.location = $.location;
    this.name = $.name;
    this.profiles = $.profiles;
    this.project = $.project;
    this.remote = $.remote;
    this.stateful = $.stateful;
    this.status = $.status;
    this.type = $.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetInstancePlainArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private GetInstancePlainArgs $;

    public Builder() {
      $ = new GetInstancePlainArgs();
    }

    public Builder(GetInstancePlainArgs defaults) {
      $ = new GetInstancePlainArgs(Objects.requireNonNull(defaults));
    }

    public Builder architecture(@Nullable String architecture) {
      $.architecture = architecture;
      return this;
    }

    public Builder description(@Nullable String description) {
      $.description = description;
      return this;
    }

    public Builder devices(@Nullable List<GetInstanceDevice> devices) {
      $.devices = devices;
      return this;
    }

    public Builder devices(GetInstanceDevice... devices) {
      return devices(List.of(devices));
    }

    public Builder ephemeral(@Nullable Boolean ephemeral) {
      $.ephemeral = ephemeral;
      return this;
    }

    public Builder location(@Nullable String location) {
      $.location = location;
      return this;
    }

    public Builder name(String name) {
      $.name = name;
      return this;
    }

    public Builder profiles(@Nullable List<String> profiles) {
      $.profiles = profiles;
      return this;
    }

    public Builder profiles(String... profiles) {
      return profiles(List.of(profiles));
    }

    public Builder project(@Nullable String project) {
      $.project = project;
      return this;
    }

    public Builder remote(@Nullable String remote) {
      $.remote = remote;
      return this;
    }

    public Builder stateful(@Nullable Boolean stateful) {
      $.stateful = stateful;
      return this;
    }

    public Builder status(@Nullable String status) {
      $.status = status;
      return this;
    }

    public Builder type(@Nullable String type) {
      $.type = type;
      return this;
    }

    public GetInstancePlainArgs build() {
      if ($.name == null) {
        throw new MissingRequiredPropertyException("GetInstancePlainArgs", "name");
      }
      return $;
    }
  }
}
