// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class GetNetworkLoadBalancerArgs extends com.pulumi.resources.InvokeArgs {

  public static final GetNetworkLoadBalancerArgs Empty = new GetNetworkLoadBalancerArgs();

  @Import(name = "backends")
  private @Nullable Output<List<GetNetworkLoadBalancerBackendArgs>> backends;

  public Optional<Output<List<GetNetworkLoadBalancerBackendArgs>>> backends() {
    return Optional.ofNullable(this.backends);
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "listenAddress", required = true)
  private Output<String> listenAddress;

  public Output<String> listenAddress() {
    return this.listenAddress;
  }

  @Import(name = "location")
  private @Nullable Output<String> location;

  public Optional<Output<String>> location() {
    return Optional.ofNullable(this.location);
  }

  @Import(name = "network", required = true)
  private Output<String> network;

  public Output<String> network() {
    return this.network;
  }

  @Import(name = "ports")
  private @Nullable Output<List<GetNetworkLoadBalancerPortArgs>> ports;

  public Optional<Output<List<GetNetworkLoadBalancerPortArgs>>> ports() {
    return Optional.ofNullable(this.ports);
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  private GetNetworkLoadBalancerArgs() {}

  private GetNetworkLoadBalancerArgs(GetNetworkLoadBalancerArgs $) {
    this.backends = $.backends;
    this.description = $.description;
    this.listenAddress = $.listenAddress;
    this.location = $.location;
    this.network = $.network;
    this.ports = $.ports;
    this.project = $.project;
    this.remote = $.remote;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetNetworkLoadBalancerArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private GetNetworkLoadBalancerArgs $;

    public Builder() {
      $ = new GetNetworkLoadBalancerArgs();
    }

    public Builder(GetNetworkLoadBalancerArgs defaults) {
      $ = new GetNetworkLoadBalancerArgs(Objects.requireNonNull(defaults));
    }

    public Builder backends(@Nullable Output<List<GetNetworkLoadBalancerBackendArgs>> backends) {
      $.backends = backends;
      return this;
    }

    public Builder backends(List<GetNetworkLoadBalancerBackendArgs> backends) {
      return backends(Output.of(backends));
    }

    public Builder backends(GetNetworkLoadBalancerBackendArgs... backends) {
      return backends(List.of(backends));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    public Builder listenAddress(Output<String> listenAddress) {
      $.listenAddress = listenAddress;
      return this;
    }

    public Builder listenAddress(String listenAddress) {
      return listenAddress(Output.of(listenAddress));
    }

    public Builder location(@Nullable Output<String> location) {
      $.location = location;
      return this;
    }

    public Builder location(String location) {
      return location(Output.of(location));
    }

    public Builder network(Output<String> network) {
      $.network = network;
      return this;
    }

    public Builder network(String network) {
      return network(Output.of(network));
    }

    public Builder ports(@Nullable Output<List<GetNetworkLoadBalancerPortArgs>> ports) {
      $.ports = ports;
      return this;
    }

    public Builder ports(List<GetNetworkLoadBalancerPortArgs> ports) {
      return ports(Output.of(ports));
    }

    public Builder ports(GetNetworkLoadBalancerPortArgs... ports) {
      return ports(List.of(ports));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public GetNetworkLoadBalancerArgs build() {
      if ($.listenAddress == null) {
        throw new MissingRequiredPropertyException("GetNetworkLoadBalancerArgs", "listenAddress");
      }
      if ($.network == null) {
        throw new MissingRequiredPropertyException("GetNetworkLoadBalancerArgs", "network");
      }
      return $;
    }
  }
}
