// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class NetworkAclState extends com.pulumi.resources.ResourceArgs {

  public static final NetworkAclState Empty = new NetworkAclState();

  @Import(name = "config")
  private @Nullable Output<Map<String, String>> config;

  public Optional<Output<Map<String, String>>> config() {
    return Optional.ofNullable(this.config);
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "egresses")
  private @Nullable Output<List<NetworkAclEgressArgs>> egresses;

  public Optional<Output<List<NetworkAclEgressArgs>>> egresses() {
    return Optional.ofNullable(this.egresses);
  }

  @Import(name = "ingresses")
  private @Nullable Output<List<NetworkAclIngressArgs>> ingresses;

  public Optional<Output<List<NetworkAclIngressArgs>>> ingresses() {
    return Optional.ofNullable(this.ingresses);
  }

  @Import(name = "name")
  private @Nullable Output<String> name;

  public Optional<Output<String>> name() {
    return Optional.ofNullable(this.name);
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  private NetworkAclState() {}

  private NetworkAclState(NetworkAclState $) {
    this.config = $.config;
    this.description = $.description;
    this.egresses = $.egresses;
    this.ingresses = $.ingresses;
    this.name = $.name;
    this.project = $.project;
    this.remote = $.remote;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(NetworkAclState defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private NetworkAclState $;

    public Builder() {
      $ = new NetworkAclState();
    }

    public Builder(NetworkAclState defaults) {
      $ = new NetworkAclState(Objects.requireNonNull(defaults));
    }

    public Builder config(@Nullable Output<Map<String, String>> config) {
      $.config = config;
      return this;
    }

    public Builder config(Map<String, String> config) {
      return config(Output.of(config));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    public Builder egresses(@Nullable Output<List<NetworkAclEgressArgs>> egresses) {
      $.egresses = egresses;
      return this;
    }

    public Builder egresses(List<NetworkAclEgressArgs> egresses) {
      return egresses(Output.of(egresses));
    }

    public Builder egresses(NetworkAclEgressArgs... egresses) {
      return egresses(List.of(egresses));
    }

    public Builder ingresses(@Nullable Output<List<NetworkAclIngressArgs>> ingresses) {
      $.ingresses = ingresses;
      return this;
    }

    public Builder ingresses(List<NetworkAclIngressArgs> ingresses) {
      return ingresses(Output.of(ingresses));
    }

    public Builder ingresses(NetworkAclIngressArgs... ingresses) {
      return ingresses(List.of(ingresses));
    }

    public Builder name(@Nullable Output<String> name) {
      $.name = name;
      return this;
    }

    public Builder name(String name) {
      return name(Output.of(name));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public NetworkAclState build() {
      return $;
    }
  }
}
