// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

public final class GetNetworkLoadBalancerPortArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetNetworkLoadBalancerPortArgs Empty = new GetNetworkLoadBalancerPortArgs();

    @Import(name = "description", required = true)
    private Output<String> description;

    public Output<String> description() {
        return this.description;
    }

    @Import(name = "listenPort", required = true)
    private Output<String> listenPort;

    public Output<String> listenPort() {
        return this.listenPort;
    }

    @Import(name = "protocol", required = true)
    private Output<String> protocol;

    public Output<String> protocol() {
        return this.protocol;
    }

    @Import(name = "targetBackends", required = true)
    private Output<List<String>> targetBackends;

    public Output<List<String>> targetBackends() {
        return this.targetBackends;
    }

    private GetNetworkLoadBalancerPortArgs() {
    }

    private GetNetworkLoadBalancerPortArgs(GetNetworkLoadBalancerPortArgs $) {
        this.description = $.description;
        this.listenPort = $.listenPort;
        this.protocol = $.protocol;
        this.targetBackends = $.targetBackends;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkLoadBalancerPortArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNetworkLoadBalancerPortArgs $;

        public Builder() {
            $ = new GetNetworkLoadBalancerPortArgs();
        }

        public Builder(GetNetworkLoadBalancerPortArgs defaults) {
            $ = new GetNetworkLoadBalancerPortArgs(Objects.requireNonNull(defaults));
        }

        public Builder description(Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder listenPort(Output<String> listenPort) {
            $.listenPort = listenPort;
            return this;
        }

        public Builder listenPort(String listenPort) {
            return listenPort(Output.of(listenPort));
        }

        public Builder protocol(Output<String> protocol) {
            $.protocol = protocol;
            return this;
        }

        public Builder protocol(String protocol) {
            return protocol(Output.of(protocol));
        }

        public Builder targetBackends(Output<List<String>> targetBackends) {
            $.targetBackends = targetBackends;
            return this;
        }

        public Builder targetBackends(List<String> targetBackends) {
            return targetBackends(Output.of(targetBackends));
        }

        public Builder targetBackends(String... targetBackends) {
            return targetBackends(List.of(targetBackends));
        }

        public GetNetworkLoadBalancerPortArgs build() {
            if ($.description == null) {
                throw new MissingRequiredPropertyException("GetNetworkLoadBalancerPortArgs", "description");
            }
            if ($.listenPort == null) {
                throw new MissingRequiredPropertyException("GetNetworkLoadBalancerPortArgs", "listenPort");
            }
            if ($.protocol == null) {
                throw new MissingRequiredPropertyException("GetNetworkLoadBalancerPortArgs", "protocol");
            }
            if ($.targetBackends == null) {
                throw new MissingRequiredPropertyException("GetNetworkLoadBalancerPortArgs", "targetBackends");
            }
            return $;
        }
    }

}
