// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class GetNetworkPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNetworkPlainArgs Empty = new GetNetworkPlainArgs();

    @Import(name = "description")
    private @Nullable String description;

    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name = "locations")
    private @Nullable List<String> locations;

    public Optional<List<String>> locations() {
        return Optional.ofNullable(this.locations);
    }

    @Import(name = "managed")
    private @Nullable Boolean managed;

    public Optional<Boolean> managed() {
        return Optional.ofNullable(this.managed);
    }

    @Import(name = "name", required = true)
    private String name;

    public String name() {
        return this.name;
    }

    @Import(name = "project")
    private @Nullable String project;

    public Optional<String> project() {
        return Optional.ofNullable(this.project);
    }

    @Import(name = "remote")
    private @Nullable String remote;

    public Optional<String> remote() {
        return Optional.ofNullable(this.remote);
    }

    @Import(name = "status")
    private @Nullable String status;

    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    @Import(name = "target")
    private @Nullable String target;

    public Optional<String> target() {
        return Optional.ofNullable(this.target);
    }

    @Import(name = "type")
    private @Nullable String type;

    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    private GetNetworkPlainArgs() {
    }

    private GetNetworkPlainArgs(GetNetworkPlainArgs $) {
        this.description = $.description;
        this.locations = $.locations;
        this.managed = $.managed;
        this.name = $.name;
        this.project = $.project;
        this.remote = $.remote;
        this.status = $.status;
        this.target = $.target;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNetworkPlainArgs $;

        public Builder() {
            $ = new GetNetworkPlainArgs();
        }

        public Builder(GetNetworkPlainArgs defaults) {
            $ = new GetNetworkPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder description(@Nullable String description) {
            $.description = description;
            return this;
        }

        public Builder locations(@Nullable List<String> locations) {
            $.locations = locations;
            return this;
        }

        public Builder locations(String... locations) {
            return locations(List.of(locations));
        }

        public Builder managed(@Nullable Boolean managed) {
            $.managed = managed;
            return this;
        }

        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public Builder project(@Nullable String project) {
            $.project = project;
            return this;
        }

        public Builder remote(@Nullable String remote) {
            $.remote = remote;
            return this;
        }

        public Builder status(@Nullable String status) {
            $.status = status;
            return this;
        }

        public Builder target(@Nullable String target) {
            $.target = target;
            return this;
        }

        public Builder type(@Nullable String type) {
            $.type = type;
            return this;
        }

        public GetNetworkPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetNetworkPlainArgs", "name");
            }
            return $;
        }
    }

}
