// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class GetNetworkZonePlainArgs extends com.pulumi.resources.InvokeArgs {

  public static final GetNetworkZonePlainArgs Empty = new GetNetworkZonePlainArgs();

  @Import(name = "description")
  private @Nullable String description;

  public Optional<String> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "name", required = true)
  private String name;

  public String name() {
    return this.name;
  }

  @Import(name = "project")
  private @Nullable String project;

  public Optional<String> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable String remote;

  public Optional<String> remote() {
    return Optional.ofNullable(this.remote);
  }

  private GetNetworkZonePlainArgs() {}

  private GetNetworkZonePlainArgs(GetNetworkZonePlainArgs $) {
    this.description = $.description;
    this.name = $.name;
    this.project = $.project;
    this.remote = $.remote;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetNetworkZonePlainArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private GetNetworkZonePlainArgs $;

    public Builder() {
      $ = new GetNetworkZonePlainArgs();
    }

    public Builder(GetNetworkZonePlainArgs defaults) {
      $ = new GetNetworkZonePlainArgs(Objects.requireNonNull(defaults));
    }

    public Builder description(@Nullable String description) {
      $.description = description;
      return this;
    }

    public Builder name(String name) {
      $.name = name;
      return this;
    }

    public Builder project(@Nullable String project) {
      $.project = project;
      return this;
    }

    public Builder remote(@Nullable String remote) {
      $.remote = remote;
      return this;
    }

    public GetNetworkZonePlainArgs build() {
      if ($.name == null) {
        throw new MissingRequiredPropertyException("GetNetworkZonePlainArgs", "name");
      }
      return $;
    }
  }
}
