// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.incus.inputs.GetNetworkAclEgressArgs;
import com.pulumi.incus.inputs.GetNetworkAclIngressArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class GetNetworkAclArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNetworkAclArgs Empty = new GetNetworkAclArgs();

    @Import(name = "description")
    private @Nullable Output<String> description;

    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name = "egresses")
    private @Nullable Output<List<GetNetworkAclEgressArgs>> egresses;

    public Optional<Output<List<GetNetworkAclEgressArgs>>> egresses() {
        return Optional.ofNullable(this.egresses);
    }

    @Import(name = "ingresses")
    private @Nullable Output<List<GetNetworkAclIngressArgs>> ingresses;

    public Optional<Output<List<GetNetworkAclIngressArgs>>> ingresses() {
        return Optional.ofNullable(this.ingresses);
    }

    @Import(name = "name", required = true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name = "project")
    private @Nullable Output<String> project;

    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    @Import(name = "remote")
    private @Nullable Output<String> remote;

    public Optional<Output<String>> remote() {
        return Optional.ofNullable(this.remote);
    }

    private GetNetworkAclArgs() {
    }

    private GetNetworkAclArgs(GetNetworkAclArgs $) {
        this.description = $.description;
        this.egresses = $.egresses;
        this.ingresses = $.ingresses;
        this.name = $.name;
        this.project = $.project;
        this.remote = $.remote;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkAclArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNetworkAclArgs $;

        public Builder() {
            $ = new GetNetworkAclArgs();
        }

        public Builder(GetNetworkAclArgs defaults) {
            $ = new GetNetworkAclArgs(Objects.requireNonNull(defaults));
        }

        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder egresses(@Nullable Output<List<GetNetworkAclEgressArgs>> egresses) {
            $.egresses = egresses;
            return this;
        }

        public Builder egresses(List<GetNetworkAclEgressArgs> egresses) {
            return egresses(Output.of(egresses));
        }

        public Builder egresses(GetNetworkAclEgressArgs... egresses) {
            return egresses(List.of(egresses));
        }

        public Builder ingresses(@Nullable Output<List<GetNetworkAclIngressArgs>> ingresses) {
            $.ingresses = ingresses;
            return this;
        }

        public Builder ingresses(List<GetNetworkAclIngressArgs> ingresses) {
            return ingresses(Output.of(ingresses));
        }

        public Builder ingresses(GetNetworkAclIngressArgs... ingresses) {
            return ingresses(List.of(ingresses));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        public Builder project(String project) {
            return project(Output.of(project));
        }

        public Builder remote(@Nullable Output<String> remote) {
            $.remote = remote;
            return this;
        }

        public Builder remote(String remote) {
            return remote(Output.of(remote));
        }

        public GetNetworkAclArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclArgs", "name");
            }
            return $;
        }
    }

}
