// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;


public final class GetNetworkForwardPortArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetNetworkForwardPortArgs Empty = new GetNetworkForwardPortArgs();

    @Import(name="description", required=true)
    private Output<String> description;

    public Output<String> description() {
        return this.description;
    }

    @Import(name="listenPort", required=true)
    private Output<String> listenPort;

    public Output<String> listenPort() {
        return this.listenPort;
    }

    @Import(name="protocol", required=true)
    private Output<String> protocol;

    public Output<String> protocol() {
        return this.protocol;
    }

    @Import(name="snat", required=true)
    private Output<Boolean> snat;

    public Output<Boolean> snat() {
        return this.snat;
    }

    @Import(name="targetAddress", required=true)
    private Output<String> targetAddress;

    public Output<String> targetAddress() {
        return this.targetAddress;
    }

    @Import(name="targetPort", required=true)
    private Output<String> targetPort;

    public Output<String> targetPort() {
        return this.targetPort;
    }

    private GetNetworkForwardPortArgs() {}

    private GetNetworkForwardPortArgs(GetNetworkForwardPortArgs $) {
        this.description = $.description;
        this.listenPort = $.listenPort;
        this.protocol = $.protocol;
        this.snat = $.snat;
        this.targetAddress = $.targetAddress;
        this.targetPort = $.targetPort;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNetworkForwardPortArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNetworkForwardPortArgs $;

        public Builder() {
            $ = new GetNetworkForwardPortArgs();
        }

        public Builder(GetNetworkForwardPortArgs defaults) {
            $ = new GetNetworkForwardPortArgs(Objects.requireNonNull(defaults));
        }

        public Builder description(Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder listenPort(Output<String> listenPort) {
            $.listenPort = listenPort;
            return this;
        }

        public Builder listenPort(String listenPort) {
            return listenPort(Output.of(listenPort));
        }

        public Builder protocol(Output<String> protocol) {
            $.protocol = protocol;
            return this;
        }

        public Builder protocol(String protocol) {
            return protocol(Output.of(protocol));
        }

        public Builder snat(Output<Boolean> snat) {
            $.snat = snat;
            return this;
        }

        public Builder snat(Boolean snat) {
            return snat(Output.of(snat));
        }

        public Builder targetAddress(Output<String> targetAddress) {
            $.targetAddress = targetAddress;
            return this;
        }

        public Builder targetAddress(String targetAddress) {
            return targetAddress(Output.of(targetAddress));
        }

        public Builder targetPort(Output<String> targetPort) {
            $.targetPort = targetPort;
            return this;
        }

        public Builder targetPort(String targetPort) {
            return targetPort(Output.of(targetPort));
        }

        public GetNetworkForwardPortArgs build() {
            if ($.description == null) {
                throw new MissingRequiredPropertyException("GetNetworkForwardPortArgs", "description");
            }
            if ($.listenPort == null) {
                throw new MissingRequiredPropertyException("GetNetworkForwardPortArgs", "listenPort");
            }
            if ($.protocol == null) {
                throw new MissingRequiredPropertyException("GetNetworkForwardPortArgs", "protocol");
            }
            if ($.snat == null) {
                throw new MissingRequiredPropertyException("GetNetworkForwardPortArgs", "snat");
            }
            if ($.targetAddress == null) {
                throw new MissingRequiredPropertyException("GetNetworkForwardPortArgs", "targetAddress");
            }
            if ($.targetPort == null) {
                throw new MissingRequiredPropertyException("GetNetworkForwardPortArgs", "targetPort");
            }
            return $;
        }
    }

}
