// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetNetworkAclEgressArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetNetworkAclEgressArgs Empty = new GetNetworkAclEgressArgs();

    @Import(name="action", required=true)
    private Output<String> action;

    public Output<String> action() {
        return this.action;
    }

    @Import(name="description", required=true)
    private Output<String> description;

    public Output<String> description() {
        return this.description;
    }

    @Import(name="destination", required=true)
    private Output<String> destination;

    public Output<String> destination() {
        return this.destination;
    }

    @Import(name="destinationPort", required=true)
    private Output<String> destinationPort;

    public Output<String> destinationPort() {
        return this.destinationPort;
    }

    @Import(name="icmpCode", required=true)
    private Output<String> icmpCode;

    public Output<String> icmpCode() {
        return this.icmpCode;
    }

    @Import(name="icmpType", required=true)
    private Output<String> icmpType;

    public Output<String> icmpType() {
        return this.icmpType;
    }

    @Import(name="protocol", required=true)
    private Output<String> protocol;

    public Output<String> protocol() {
        return this.protocol;
    }

    @Import(name="source", required=true)
    private Output<String> source;

    public Output<String> source() {
        return this.source;
    }

    @Import(name="sourcePort", required=true)
    private Output<String> sourcePort;

    public Output<String> sourcePort() {
        return this.sourcePort;
    }

    @Import(name="state", required=true)
    private Output<String> state;

    public Output<String> state() {
        return this.state;
    }

    private GetNetworkAclEgressArgs() {}

    private GetNetworkAclEgressArgs(GetNetworkAclEgressArgs $) {
        this.action = $.action;
        this.description = $.description;
        this.destination = $.destination;
        this.destinationPort = $.destinationPort;
        this.icmpCode = $.icmpCode;
        this.icmpType = $.icmpType;
        this.protocol = $.protocol;
        this.source = $.source;
        this.sourcePort = $.sourcePort;
        this.state = $.state;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNetworkAclEgressArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNetworkAclEgressArgs $;

        public Builder() {
            $ = new GetNetworkAclEgressArgs();
        }

        public Builder(GetNetworkAclEgressArgs defaults) {
            $ = new GetNetworkAclEgressArgs(Objects.requireNonNull(defaults));
        }

        public Builder action(Output<String> action) {
            $.action = action;
            return this;
        }

        public Builder action(String action) {
            return action(Output.of(action));
        }

        public Builder description(Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder destination(Output<String> destination) {
            $.destination = destination;
            return this;
        }

        public Builder destination(String destination) {
            return destination(Output.of(destination));
        }

        public Builder destinationPort(Output<String> destinationPort) {
            $.destinationPort = destinationPort;
            return this;
        }

        public Builder destinationPort(String destinationPort) {
            return destinationPort(Output.of(destinationPort));
        }

        public Builder icmpCode(Output<String> icmpCode) {
            $.icmpCode = icmpCode;
            return this;
        }

        public Builder icmpCode(String icmpCode) {
            return icmpCode(Output.of(icmpCode));
        }

        public Builder icmpType(Output<String> icmpType) {
            $.icmpType = icmpType;
            return this;
        }

        public Builder icmpType(String icmpType) {
            return icmpType(Output.of(icmpType));
        }

        public Builder protocol(Output<String> protocol) {
            $.protocol = protocol;
            return this;
        }

        public Builder protocol(String protocol) {
            return protocol(Output.of(protocol));
        }

        public Builder source(Output<String> source) {
            $.source = source;
            return this;
        }

        public Builder source(String source) {
            return source(Output.of(source));
        }

        public Builder sourcePort(Output<String> sourcePort) {
            $.sourcePort = sourcePort;
            return this;
        }

        public Builder sourcePort(String sourcePort) {
            return sourcePort(Output.of(sourcePort));
        }

        public Builder state(Output<String> state) {
            $.state = state;
            return this;
        }

        public Builder state(String state) {
            return state(Output.of(state));
        }

        public GetNetworkAclEgressArgs build() {
            if ($.action == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "action");
            }
            if ($.description == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "description");
            }
            if ($.destination == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "destination");
            }
            if ($.destinationPort == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "destinationPort");
            }
            if ($.icmpCode == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "icmpCode");
            }
            if ($.icmpType == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "icmpType");
            }
            if ($.protocol == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "protocol");
            }
            if ($.source == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "source");
            }
            if ($.sourcePort == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "sourcePort");
            }
            if ($.state == null) {
                throw new MissingRequiredPropertyException("GetNetworkAclEgressArgs", "state");
            }
            return $;
        }
    }

}
