// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;

public final class GetNetworkAclIngress extends com.pulumi.resources.InvokeArgs {

  public static final GetNetworkAclIngress Empty = new GetNetworkAclIngress();

  @Import(name = "action", required = true)
  private String action;

  public String action() {
    return this.action;
  }

  @Import(name = "description", required = true)
  private String description;

  public String description() {
    return this.description;
  }

  @Import(name = "destination", required = true)
  private String destination;

  public String destination() {
    return this.destination;
  }

  @Import(name = "destinationPort", required = true)
  private String destinationPort;

  public String destinationPort() {
    return this.destinationPort;
  }

  @Import(name = "icmpCode", required = true)
  private String icmpCode;

  public String icmpCode() {
    return this.icmpCode;
  }

  @Import(name = "icmpType", required = true)
  private String icmpType;

  public String icmpType() {
    return this.icmpType;
  }

  @Import(name = "protocol", required = true)
  private String protocol;

  public String protocol() {
    return this.protocol;
  }

  @Import(name = "source", required = true)
  private String source;

  public String source() {
    return this.source;
  }

  @Import(name = "sourcePort", required = true)
  private String sourcePort;

  public String sourcePort() {
    return this.sourcePort;
  }

  @Import(name = "state", required = true)
  private String state;

  public String state() {
    return this.state;
  }

  private GetNetworkAclIngress() {}

  private GetNetworkAclIngress(GetNetworkAclIngress $) {
    this.action = $.action;
    this.description = $.description;
    this.destination = $.destination;
    this.destinationPort = $.destinationPort;
    this.icmpCode = $.icmpCode;
    this.icmpType = $.icmpType;
    this.protocol = $.protocol;
    this.source = $.source;
    this.sourcePort = $.sourcePort;
    this.state = $.state;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetNetworkAclIngress defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private GetNetworkAclIngress $;

    public Builder() {
      $ = new GetNetworkAclIngress();
    }

    public Builder(GetNetworkAclIngress defaults) {
      $ = new GetNetworkAclIngress(Objects.requireNonNull(defaults));
    }

    public Builder action(String action) {
      $.action = action;
      return this;
    }

    public Builder description(String description) {
      $.description = description;
      return this;
    }

    public Builder destination(String destination) {
      $.destination = destination;
      return this;
    }

    public Builder destinationPort(String destinationPort) {
      $.destinationPort = destinationPort;
      return this;
    }

    public Builder icmpCode(String icmpCode) {
      $.icmpCode = icmpCode;
      return this;
    }

    public Builder icmpType(String icmpType) {
      $.icmpType = icmpType;
      return this;
    }

    public Builder protocol(String protocol) {
      $.protocol = protocol;
      return this;
    }

    public Builder source(String source) {
      $.source = source;
      return this;
    }

    public Builder sourcePort(String sourcePort) {
      $.sourcePort = sourcePort;
      return this;
    }

    public Builder state(String state) {
      $.state = state;
      return this;
    }

    public GetNetworkAclIngress build() {
      if ($.action == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "action");
      }
      if ($.description == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "description");
      }
      if ($.destination == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "destination");
      }
      if ($.destinationPort == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "destinationPort");
      }
      if ($.icmpCode == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "icmpCode");
      }
      if ($.icmpType == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "icmpType");
      }
      if ($.protocol == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "protocol");
      }
      if ($.source == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "source");
      }
      if ($.sourcePort == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "sourcePort");
      }
      if ($.state == null) {
        throw new MissingRequiredPropertyException("GetNetworkAclIngress", "state");
      }
      return $;
    }
  }
}
