// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetStorageBucketPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetStorageBucketPlainArgs Empty = new GetStorageBucketPlainArgs();

    @Import(name="description")
    private @Nullable String description;

    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name="location")
    private @Nullable String location;

    public Optional<String> location() {
        return Optional.ofNullable(this.location);
    }

    @Import(name="name", required=true)
    private String name;

    public String name() {
        return this.name;
    }

    @Import(name="project")
    private @Nullable String project;

    public Optional<String> project() {
        return Optional.ofNullable(this.project);
    }

    @Import(name="remote")
    private @Nullable String remote;

    public Optional<String> remote() {
        return Optional.ofNullable(this.remote);
    }

    @Import(name="s3Url")
    private @Nullable String s3Url;

    public Optional<String> s3Url() {
        return Optional.ofNullable(this.s3Url);
    }

    @Import(name="storagePool", required=true)
    private String storagePool;

    public String storagePool() {
        return this.storagePool;
    }

    @Import(name="target")
    private @Nullable String target;

    public Optional<String> target() {
        return Optional.ofNullable(this.target);
    }

    private GetStorageBucketPlainArgs() {}

    private GetStorageBucketPlainArgs(GetStorageBucketPlainArgs $) {
        this.description = $.description;
        this.location = $.location;
        this.name = $.name;
        this.project = $.project;
        this.remote = $.remote;
        this.s3Url = $.s3Url;
        this.storagePool = $.storagePool;
        this.target = $.target;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetStorageBucketPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetStorageBucketPlainArgs $;

        public Builder() {
            $ = new GetStorageBucketPlainArgs();
        }

        public Builder(GetStorageBucketPlainArgs defaults) {
            $ = new GetStorageBucketPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder description(@Nullable String description) {
            $.description = description;
            return this;
        }

        public Builder location(@Nullable String location) {
            $.location = location;
            return this;
        }

        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public Builder project(@Nullable String project) {
            $.project = project;
            return this;
        }

        public Builder remote(@Nullable String remote) {
            $.remote = remote;
            return this;
        }

        public Builder s3Url(@Nullable String s3Url) {
            $.s3Url = s3Url;
            return this;
        }

        public Builder storagePool(String storagePool) {
            $.storagePool = storagePool;
            return this;
        }

        public Builder target(@Nullable String target) {
            $.target = target;
            return this;
        }

        public GetStorageBucketPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetStorageBucketPlainArgs", "name");
            }
            if ($.storagePool == null) {
                throw new MissingRequiredPropertyException("GetStorageBucketPlainArgs", "storagePool");
            }
            return $;
        }
    }

}
