// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ImageSourceImageArgs extends com.pulumi.resources.ResourceArgs {

    public static final ImageSourceImageArgs Empty = new ImageSourceImageArgs();

    @Import(name="architecture")
    private @Nullable Output<String> architecture;

    public Optional<Output<String>> architecture() {
        return Optional.ofNullable(this.architecture);
    }

    @Import(name="copyAliases")
    private @Nullable Output<Boolean> copyAliases;

    public Optional<Output<Boolean>> copyAliases() {
        return Optional.ofNullable(this.copyAliases);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="remote", required=true)
    private Output<String> remote;

    public Output<String> remote() {
        return this.remote;
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private ImageSourceImageArgs() {}

    private ImageSourceImageArgs(ImageSourceImageArgs $) {
        this.architecture = $.architecture;
        this.copyAliases = $.copyAliases;
        this.name = $.name;
        this.remote = $.remote;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ImageSourceImageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ImageSourceImageArgs $;

        public Builder() {
            $ = new ImageSourceImageArgs();
        }

        public Builder(ImageSourceImageArgs defaults) {
            $ = new ImageSourceImageArgs(Objects.requireNonNull(defaults));
        }

        public Builder architecture(@Nullable Output<String> architecture) {
            $.architecture = architecture;
            return this;
        }

        public Builder architecture(String architecture) {
            return architecture(Output.of(architecture));
        }

        public Builder copyAliases(@Nullable Output<Boolean> copyAliases) {
            $.copyAliases = copyAliases;
            return this;
        }

        public Builder copyAliases(Boolean copyAliases) {
            return copyAliases(Output.of(copyAliases));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder remote(Output<String> remote) {
            $.remote = remote;
            return this;
        }

        public Builder remote(String remote) {
            return remote(Output.of(remote));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ImageSourceImageArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ImageSourceImageArgs", "name");
            }
            if ($.remote == null) {
                throw new MissingRequiredPropertyException("ImageSourceImageArgs", "remote");
            }
            return $;
        }
    }

}
