// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class InstanceSnapshotState extends com.pulumi.resources.ResourceArgs {

    public static final InstanceSnapshotState Empty = new InstanceSnapshotState();

    @Import(name = "createdAt")
    private @Nullable Output<Double> createdAt;

    public Optional<Output<Double>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    @Import(name = "instance")
    private @Nullable Output<String> instance;

    public Optional<Output<String>> instance() {
        return Optional.ofNullable(this.instance);
    }

    @Import(name = "name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name = "project")
    private @Nullable Output<String> project;

    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    @Import(name = "remote")
    private @Nullable Output<String> remote;

    public Optional<Output<String>> remote() {
        return Optional.ofNullable(this.remote);
    }

    @Import(name = "stateful")
    private @Nullable Output<Boolean> stateful;

    public Optional<Output<Boolean>> stateful() {
        return Optional.ofNullable(this.stateful);
    }

    private InstanceSnapshotState() {
    }

    private InstanceSnapshotState(InstanceSnapshotState $) {
        this.createdAt = $.createdAt;
        this.instance = $.instance;
        this.name = $.name;
        this.project = $.project;
        this.remote = $.remote;
        this.stateful = $.stateful;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(InstanceSnapshotState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InstanceSnapshotState $;

        public Builder() {
            $ = new InstanceSnapshotState();
        }

        public Builder(InstanceSnapshotState defaults) {
            $ = new InstanceSnapshotState(Objects.requireNonNull(defaults));
        }

        public Builder createdAt(@Nullable Output<Double> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(Double createdAt) {
            return createdAt(Output.of(createdAt));
        }

        public Builder instance(@Nullable Output<String> instance) {
            $.instance = instance;
            return this;
        }

        public Builder instance(String instance) {
            return instance(Output.of(instance));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        public Builder project(String project) {
            return project(Output.of(project));
        }

        public Builder remote(@Nullable Output<String> remote) {
            $.remote = remote;
            return this;
        }

        public Builder remote(String remote) {
            return remote(Output.of(remote));
        }

        public Builder stateful(@Nullable Output<Boolean> stateful) {
            $.stateful = stateful;
            return this;
        }

        public Builder stateful(Boolean stateful) {
            return stateful(Output.of(stateful));
        }

        public InstanceSnapshotState build() {
            return $;
        }
    }

}
