// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class InstanceWaitForArgs extends com.pulumi.resources.ResourceArgs {

    public static final InstanceWaitForArgs Empty = new InstanceWaitForArgs();

    @Import(name="delay")
    private @Nullable Output<String> delay;

    public Optional<Output<String>> delay() {
        return Optional.ofNullable(this.delay);
    }

    @Import(name="nic")
    private @Nullable Output<String> nic;

    public Optional<Output<String>> nic() {
        return Optional.ofNullable(this.nic);
    }

    @Import(name="type", required=true)
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    private InstanceWaitForArgs() {}

    private InstanceWaitForArgs(InstanceWaitForArgs $) {
        this.delay = $.delay;
        this.nic = $.nic;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(InstanceWaitForArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InstanceWaitForArgs $;

        public Builder() {
            $ = new InstanceWaitForArgs();
        }

        public Builder(InstanceWaitForArgs defaults) {
            $ = new InstanceWaitForArgs(Objects.requireNonNull(defaults));
        }

        public Builder delay(@Nullable Output<String> delay) {
            $.delay = delay;
            return this;
        }

        public Builder delay(String delay) {
            return delay(Output.of(delay));
        }

        public Builder nic(@Nullable Output<String> nic) {
            $.nic = nic;
            return this;
        }

        public Builder nic(String nic) {
            return nic(Output.of(nic));
        }

        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public InstanceWaitForArgs build() {
            if ($.type == null) {
                throw new MissingRequiredPropertyException("InstanceWaitForArgs", "type");
            }
            return $;
        }
    }

}
