// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkLbBackendArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkLbBackendArgs Empty = new NetworkLbBackendArgs();

    /**
     * LB backend description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return LB backend description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * LB backend name
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return LB backend name
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * LB backend target address
     * 
     */
    @Import(name="targetAddress", required=true)
    private Output<String> targetAddress;

    /**
     * @return LB backend target address
     * 
     */
    public Output<String> targetAddress() {
        return this.targetAddress;
    }

    /**
     * LB backend target port
     * 
     */
    @Import(name="targetPort")
    private @Nullable Output<String> targetPort;

    /**
     * @return LB backend target port
     * 
     */
    public Optional<Output<String>> targetPort() {
        return Optional.ofNullable(this.targetPort);
    }

    private NetworkLbBackendArgs() {}

    private NetworkLbBackendArgs(NetworkLbBackendArgs $) {
        this.description = $.description;
        this.name = $.name;
        this.targetAddress = $.targetAddress;
        this.targetPort = $.targetPort;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkLbBackendArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkLbBackendArgs $;

        public Builder() {
            $ = new NetworkLbBackendArgs();
        }

        public Builder(NetworkLbBackendArgs defaults) {
            $ = new NetworkLbBackendArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description LB backend description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description LB backend description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name LB backend name
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name LB backend name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param targetAddress LB backend target address
         * 
         * @return builder
         * 
         */
        public Builder targetAddress(Output<String> targetAddress) {
            $.targetAddress = targetAddress;
            return this;
        }

        /**
         * @param targetAddress LB backend target address
         * 
         * @return builder
         * 
         */
        public Builder targetAddress(String targetAddress) {
            return targetAddress(Output.of(targetAddress));
        }

        /**
         * @param targetPort LB backend target port
         * 
         * @return builder
         * 
         */
        public Builder targetPort(@Nullable Output<String> targetPort) {
            $.targetPort = targetPort;
            return this;
        }

        /**
         * @param targetPort LB backend target port
         * 
         * @return builder
         * 
         */
        public Builder targetPort(String targetPort) {
            return targetPort(Output.of(targetPort));
        }

        public NetworkLbBackendArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("NetworkLbBackendArgs", "name");
            }
            if ($.targetAddress == null) {
                throw new MissingRequiredPropertyException("NetworkLbBackendArgs", "targetAddress");
            }
            return $;
        }
    }

}
