// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkPeerState extends com.pulumi.resources.ResourceArgs {

    public static final NetworkPeerState Empty = new NetworkPeerState();

    @Import(name="config")
    private @Nullable Output<Map<String,String>> config;

    public Optional<Output<Map<String,String>>> config() {
        return Optional.ofNullable(this.config);
    }

    @Import(name="description")
    private @Nullable Output<String> description;

    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="network")
    private @Nullable Output<String> network;

    public Optional<Output<String>> network() {
        return Optional.ofNullable(this.network);
    }

    @Import(name="project")
    private @Nullable Output<String> project;

    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    @Import(name="remote")
    private @Nullable Output<String> remote;

    public Optional<Output<String>> remote() {
        return Optional.ofNullable(this.remote);
    }

    @Import(name="status")
    private @Nullable Output<String> status;

    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    @Import(name="targetIntegration")
    private @Nullable Output<String> targetIntegration;

    public Optional<Output<String>> targetIntegration() {
        return Optional.ofNullable(this.targetIntegration);
    }

    @Import(name="targetNetwork")
    private @Nullable Output<String> targetNetwork;

    public Optional<Output<String>> targetNetwork() {
        return Optional.ofNullable(this.targetNetwork);
    }

    @Import(name="targetProject")
    private @Nullable Output<String> targetProject;

    public Optional<Output<String>> targetProject() {
        return Optional.ofNullable(this.targetProject);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private NetworkPeerState() {}

    private NetworkPeerState(NetworkPeerState $) {
        this.config = $.config;
        this.description = $.description;
        this.name = $.name;
        this.network = $.network;
        this.project = $.project;
        this.remote = $.remote;
        this.status = $.status;
        this.targetIntegration = $.targetIntegration;
        this.targetNetwork = $.targetNetwork;
        this.targetProject = $.targetProject;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkPeerState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkPeerState $;

        public Builder() {
            $ = new NetworkPeerState();
        }

        public Builder(NetworkPeerState defaults) {
            $ = new NetworkPeerState(Objects.requireNonNull(defaults));
        }

        public Builder config(@Nullable Output<Map<String,String>> config) {
            $.config = config;
            return this;
        }

        public Builder config(Map<String,String> config) {
            return config(Output.of(config));
        }

        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder network(@Nullable Output<String> network) {
            $.network = network;
            return this;
        }

        public Builder network(String network) {
            return network(Output.of(network));
        }

        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        public Builder project(String project) {
            return project(Output.of(project));
        }

        public Builder remote(@Nullable Output<String> remote) {
            $.remote = remote;
            return this;
        }

        public Builder remote(String remote) {
            return remote(Output.of(remote));
        }

        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        public Builder status(String status) {
            return status(Output.of(status));
        }

        public Builder targetIntegration(@Nullable Output<String> targetIntegration) {
            $.targetIntegration = targetIntegration;
            return this;
        }

        public Builder targetIntegration(String targetIntegration) {
            return targetIntegration(Output.of(targetIntegration));
        }

        public Builder targetNetwork(@Nullable Output<String> targetNetwork) {
            $.targetNetwork = targetNetwork;
            return this;
        }

        public Builder targetNetwork(String targetNetwork) {
            return targetNetwork(Output.of(targetNetwork));
        }

        public Builder targetProject(@Nullable Output<String> targetProject) {
            $.targetProject = targetProject;
            return this;
        }

        public Builder targetProject(String targetProject) {
            return targetProject(Output.of(targetProject));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public NetworkPeerState build() {
            return $;
        }
    }

}
