// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkForwardPortArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkForwardPortArgs Empty = new NetworkForwardPortArgs();

    /**
     * Port description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Port description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Listen port to forward
     * 
     */
    @Import(name="listenPort", required=true)
    private Output<String> listenPort;

    /**
     * @return Listen port to forward
     * 
     */
    public Output<String> listenPort() {
        return this.listenPort;
    }

    /**
     * Port protocol
     * 
     */
    @Import(name="protocol")
    private @Nullable Output<String> protocol;

    /**
     * @return Port protocol
     * 
     */
    public Optional<Output<String>> protocol() {
        return Optional.ofNullable(this.protocol);
    }

    /**
     * Target address to forward listen port to
     * 
     */
    @Import(name="targetAddress", required=true)
    private Output<String> targetAddress;

    /**
     * @return Target address to forward listen port to
     * 
     */
    public Output<String> targetAddress() {
        return this.targetAddress;
    }

    /**
     * Target port to forward listen port to
     * 
     */
    @Import(name="targetPort", required=true)
    private Output<String> targetPort;

    /**
     * @return Target port to forward listen port to
     * 
     */
    public Output<String> targetPort() {
        return this.targetPort;
    }

    private NetworkForwardPortArgs() {}

    private NetworkForwardPortArgs(NetworkForwardPortArgs $) {
        this.description = $.description;
        this.listenPort = $.listenPort;
        this.protocol = $.protocol;
        this.targetAddress = $.targetAddress;
        this.targetPort = $.targetPort;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkForwardPortArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkForwardPortArgs $;

        public Builder() {
            $ = new NetworkForwardPortArgs();
        }

        public Builder(NetworkForwardPortArgs defaults) {
            $ = new NetworkForwardPortArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Port description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Port description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param listenPort Listen port to forward
         * 
         * @return builder
         * 
         */
        public Builder listenPort(Output<String> listenPort) {
            $.listenPort = listenPort;
            return this;
        }

        /**
         * @param listenPort Listen port to forward
         * 
         * @return builder
         * 
         */
        public Builder listenPort(String listenPort) {
            return listenPort(Output.of(listenPort));
        }

        /**
         * @param protocol Port protocol
         * 
         * @return builder
         * 
         */
        public Builder protocol(@Nullable Output<String> protocol) {
            $.protocol = protocol;
            return this;
        }

        /**
         * @param protocol Port protocol
         * 
         * @return builder
         * 
         */
        public Builder protocol(String protocol) {
            return protocol(Output.of(protocol));
        }

        /**
         * @param targetAddress Target address to forward listen port to
         * 
         * @return builder
         * 
         */
        public Builder targetAddress(Output<String> targetAddress) {
            $.targetAddress = targetAddress;
            return this;
        }

        /**
         * @param targetAddress Target address to forward listen port to
         * 
         * @return builder
         * 
         */
        public Builder targetAddress(String targetAddress) {
            return targetAddress(Output.of(targetAddress));
        }

        /**
         * @param targetPort Target port to forward listen port to
         * 
         * @return builder
         * 
         */
        public Builder targetPort(Output<String> targetPort) {
            $.targetPort = targetPort;
            return this;
        }

        /**
         * @param targetPort Target port to forward listen port to
         * 
         * @return builder
         * 
         */
        public Builder targetPort(String targetPort) {
            return targetPort(Output.of(targetPort));
        }

        public NetworkForwardPortArgs build() {
            if ($.listenPort == null) {
                throw new MissingRequiredPropertyException("NetworkForwardPortArgs", "listenPort");
            }
            if ($.targetAddress == null) {
                throw new MissingRequiredPropertyException("NetworkForwardPortArgs", "targetAddress");
            }
            if ($.targetPort == null) {
                throw new MissingRequiredPropertyException("NetworkForwardPortArgs", "targetPort");
            }
            return $;
        }
    }

}
