// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class NetworkState extends com.pulumi.resources.ResourceArgs {

  public static final NetworkState Empty = new NetworkState();

  @Import(name = "config")
  private @Nullable Output<Map<String, String>> config;

  public Optional<Output<Map<String, String>>> config() {
    return Optional.ofNullable(this.config);
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "managed")
  private @Nullable Output<Boolean> managed;

  public Optional<Output<Boolean>> managed() {
    return Optional.ofNullable(this.managed);
  }

  @Import(name = "name")
  private @Nullable Output<String> name;

  public Optional<Output<String>> name() {
    return Optional.ofNullable(this.name);
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "target")
  private @Nullable Output<String> target;

  public Optional<Output<String>> target() {
    return Optional.ofNullable(this.target);
  }

  @Import(name = "type")
  private @Nullable Output<String> type;

  public Optional<Output<String>> type() {
    return Optional.ofNullable(this.type);
  }

  private NetworkState() {}

  private NetworkState(NetworkState $) {
    this.config = $.config;
    this.description = $.description;
    this.managed = $.managed;
    this.name = $.name;
    this.project = $.project;
    this.remote = $.remote;
    this.target = $.target;
    this.type = $.type;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(NetworkState defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private NetworkState $;

    public Builder() {
      $ = new NetworkState();
    }

    public Builder(NetworkState defaults) {
      $ = new NetworkState(Objects.requireNonNull(defaults));
    }

    public Builder config(@Nullable Output<Map<String, String>> config) {
      $.config = config;
      return this;
    }

    public Builder config(Map<String, String> config) {
      return config(Output.of(config));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    public Builder managed(@Nullable Output<Boolean> managed) {
      $.managed = managed;
      return this;
    }

    public Builder managed(Boolean managed) {
      return managed(Output.of(managed));
    }

    public Builder name(@Nullable Output<String> name) {
      $.name = name;
      return this;
    }

    public Builder name(String name) {
      return name(Output.of(name));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public Builder target(@Nullable Output<String> target) {
      $.target = target;
      return this;
    }

    public Builder target(String target) {
      return target(Output.of(target));
    }

    public Builder type(@Nullable Output<String> type) {
      $.type = type;
      return this;
    }

    public Builder type(String type) {
      return type(Output.of(type));
    }

    public NetworkState build() {
      return $;
    }
  }
}
