// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;


public final class ProfileDeviceArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProfileDeviceArgs Empty = new ProfileDeviceArgs();

    /**
     * Device name
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Device name
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Device properties
     * 
     */
    @Import(name="properties", required=true)
    private Output<Map<String,String>> properties;

    /**
     * @return Device properties
     * 
     */
    public Output<Map<String,String>> properties() {
        return this.properties;
    }

    /**
     * Device type
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return Device type
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private ProfileDeviceArgs() {}

    private ProfileDeviceArgs(ProfileDeviceArgs $) {
        this.name = $.name;
        this.properties = $.properties;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProfileDeviceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProfileDeviceArgs $;

        public Builder() {
            $ = new ProfileDeviceArgs();
        }

        public Builder(ProfileDeviceArgs defaults) {
            $ = new ProfileDeviceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Device name
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Device name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param properties Device properties
         * 
         * @return builder
         * 
         */
        public Builder properties(Output<Map<String,String>> properties) {
            $.properties = properties;
            return this;
        }

        /**
         * @param properties Device properties
         * 
         * @return builder
         * 
         */
        public Builder properties(Map<String,String> properties) {
            return properties(Output.of(properties));
        }

        /**
         * @param type Device type
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Device type
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ProfileDeviceArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ProfileDeviceArgs", "name");
            }
            if ($.properties == null) {
                throw new MissingRequiredPropertyException("ProfileDeviceArgs", "properties");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("ProfileDeviceArgs", "type");
            }
            return $;
        }
    }

}
