// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.incus.inputs.ProfileDeviceArgs;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProfileState extends com.pulumi.resources.ResourceArgs {

    public static final ProfileState Empty = new ProfileState();

    @Import(name="config")
    private @Nullable Output<Map<String,String>> config;

    public Optional<Output<Map<String,String>>> config() {
        return Optional.ofNullable(this.config);
    }

    @Import(name="description")
    private @Nullable Output<String> description;

    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Profile device
     * 
     */
    @Import(name="devices")
    private @Nullable Output<List<ProfileDeviceArgs>> devices;

    /**
     * @return Profile device
     * 
     */
    public Optional<Output<List<ProfileDeviceArgs>>> devices() {
        return Optional.ofNullable(this.devices);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="project")
    private @Nullable Output<String> project;

    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    @Import(name="remote")
    private @Nullable Output<String> remote;

    public Optional<Output<String>> remote() {
        return Optional.ofNullable(this.remote);
    }

    private ProfileState() {}

    private ProfileState(ProfileState $) {
        this.config = $.config;
        this.description = $.description;
        this.devices = $.devices;
        this.name = $.name;
        this.project = $.project;
        this.remote = $.remote;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProfileState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProfileState $;

        public Builder() {
            $ = new ProfileState();
        }

        public Builder(ProfileState defaults) {
            $ = new ProfileState(Objects.requireNonNull(defaults));
        }

        public Builder config(@Nullable Output<Map<String,String>> config) {
            $.config = config;
            return this;
        }

        public Builder config(Map<String,String> config) {
            return config(Output.of(config));
        }

        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param devices Profile device
         * 
         * @return builder
         * 
         */
        public Builder devices(@Nullable Output<List<ProfileDeviceArgs>> devices) {
            $.devices = devices;
            return this;
        }

        /**
         * @param devices Profile device
         * 
         * @return builder
         * 
         */
        public Builder devices(List<ProfileDeviceArgs> devices) {
            return devices(Output.of(devices));
        }

        /**
         * @param devices Profile device
         * 
         * @return builder
         * 
         */
        public Builder devices(ProfileDeviceArgs... devices) {
            return devices(List.of(devices));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        public Builder project(String project) {
            return project(Output.of(project));
        }

        public Builder remote(@Nullable Output<String> remote) {
            $.remote = remote;
            return this;
        }

        public Builder remote(String remote) {
            return remote(Output.of(remote));
        }

        public ProfileState build() {
            return $;
        }
    }

}
