// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class StorageBucketKeyState extends com.pulumi.resources.ResourceArgs {

    public static final StorageBucketKeyState Empty = new StorageBucketKeyState();

    @Import(name = "accessKey")
    private @Nullable Output<String> accessKey;

    public Optional<Output<String>> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    @Import(name = "description")
    private @Nullable Output<String> description;

    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name = "name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name = "pool")
    private @Nullable Output<String> pool;

    public Optional<Output<String>> pool() {
        return Optional.ofNullable(this.pool);
    }

    @Import(name = "project")
    private @Nullable Output<String> project;

    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    @Import(name = "remote")
    private @Nullable Output<String> remote;

    public Optional<Output<String>> remote() {
        return Optional.ofNullable(this.remote);
    }

    @Import(name = "role")
    private @Nullable Output<String> role;

    public Optional<Output<String>> role() {
        return Optional.ofNullable(this.role);
    }

    @Import(name = "secretKey")
    private @Nullable Output<String> secretKey;

    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    @Import(name = "storageBucket")
    private @Nullable Output<String> storageBucket;

    public Optional<Output<String>> storageBucket() {
        return Optional.ofNullable(this.storageBucket);
    }

    private StorageBucketKeyState() {
    }

    private StorageBucketKeyState(StorageBucketKeyState $) {
        this.accessKey = $.accessKey;
        this.description = $.description;
        this.name = $.name;
        this.pool = $.pool;
        this.project = $.project;
        this.remote = $.remote;
        this.role = $.role;
        this.secretKey = $.secretKey;
        this.storageBucket = $.storageBucket;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(StorageBucketKeyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private StorageBucketKeyState $;

        public Builder() {
            $ = new StorageBucketKeyState();
        }

        public Builder(StorageBucketKeyState defaults) {
            $ = new StorageBucketKeyState(Objects.requireNonNull(defaults));
        }

        public Builder accessKey(@Nullable Output<String> accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        public Builder accessKey(String accessKey) {
            return accessKey(Output.of(accessKey));
        }

        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder pool(@Nullable Output<String> pool) {
            $.pool = pool;
            return this;
        }

        public Builder pool(String pool) {
            return pool(Output.of(pool));
        }

        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        public Builder project(String project) {
            return project(Output.of(project));
        }

        public Builder remote(@Nullable Output<String> remote) {
            $.remote = remote;
            return this;
        }

        public Builder remote(String remote) {
            return remote(Output.of(remote));
        }

        public Builder role(@Nullable Output<String> role) {
            $.role = role;
            return this;
        }

        public Builder role(String role) {
            return role(Output.of(role));
        }

        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        public Builder storageBucket(@Nullable Output<String> storageBucket) {
            $.storageBucket = storageBucket;
            return this;
        }

        public Builder storageBucket(String storageBucket) {
            return storageBucket(Output.of(storageBucket));
        }

        public StorageBucketKeyState build() {
            return $;
        }
    }

}
