// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class StoragePoolState extends com.pulumi.resources.ResourceArgs {

  public static final StoragePoolState Empty = new StoragePoolState();

  @Import(name = "config")
  private @Nullable Output<Map<String, String>> config;

  public Optional<Output<Map<String, String>>> config() {
    return Optional.ofNullable(this.config);
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "driver")
  private @Nullable Output<String> driver;

  public Optional<Output<String>> driver() {
    return Optional.ofNullable(this.driver);
  }

  @Import(name = "name")
  private @Nullable Output<String> name;

  public Optional<Output<String>> name() {
    return Optional.ofNullable(this.name);
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "target")
  private @Nullable Output<String> target;

  public Optional<Output<String>> target() {
    return Optional.ofNullable(this.target);
  }

  private StoragePoolState() {}

  private StoragePoolState(StoragePoolState $) {
    this.config = $.config;
    this.description = $.description;
    this.driver = $.driver;
    this.name = $.name;
    this.project = $.project;
    this.remote = $.remote;
    this.target = $.target;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(StoragePoolState defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private StoragePoolState $;

    public Builder() {
      $ = new StoragePoolState();
    }

    public Builder(StoragePoolState defaults) {
      $ = new StoragePoolState(Objects.requireNonNull(defaults));
    }

    public Builder config(@Nullable Output<Map<String, String>> config) {
      $.config = config;
      return this;
    }

    public Builder config(Map<String, String> config) {
      return config(Output.of(config));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    public Builder driver(@Nullable Output<String> driver) {
      $.driver = driver;
      return this;
    }

    public Builder driver(String driver) {
      return driver(Output.of(driver));
    }

    public Builder name(@Nullable Output<String> name) {
      $.name = name;
      return this;
    }

    public Builder name(String name) {
      return name(Output.of(name));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public Builder target(@Nullable Output<String> target) {
      $.target = target;
      return this;
    }

    public Builder target(String target) {
      return target(Output.of(target));
    }

    public StoragePoolState build() {
      return $;
    }
  }
}
