---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: config.porch.kpt.dev|PackageVariant|porch-system|storage-openebs-zfs
    kpt.dev/package-layer: gitops
    kpt.dev/package-name: porch-resources
  name: storage-openebs-zfs
  namespace: porch-system
spec:
  adoptionPolicy: adoptNone
  deletionPolicy: delete
  downstream:
    package: storage-openebs-zfs
    repo: alcide-state
  labels:
    cluster-name: alcide
    nxmatic.dev/app: openebs-zfs
    nxmatic.dev/component: storage
  packageContext:
    data:
      cluster-env: dave
      cluster-name: alcide
  pipeline:
    mutators:
      - configMap:
          kubelet-dir: /var/lib/kubelet
          zfs-pool-name: tank
        image: ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.2
  upstream:
    package: storage-openebs-zfs
    repo: alcide-catalog
