---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: config.porch.kpt.dev|PackageVariant|porch-system|mesh-headscale
    kpt.dev/package-layer: gitops
    kpt.dev/package-name: porch-resources
  name: mesh-headscale
  namespace: porch-system
spec:
  adoptionPolicy: adoptNone
  deletionPolicy: delete
  downstream:
    package: mesh/headscale
    repo: alcide-state
  labels:
    cluster-name: alcide
    nxmatic.dev/app: headscale
    nxmatic.dev/component: mesh
  packageContext:
    data:
      cluster-env: dave
      cluster-name: alcide
  pipeline:
    mutators:
      - configMap:
          cluster-name: alcide
          darwin-host: alcide
          headscale-lb-ip: 10.80.56.65
          home-lan-pool: 10.80.56.64/26
          vip-network-cidr: ${cluster-vip-network-cidr}
        image: ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.2
  upstream:
    package: mesh/headscale
    repo: alcide-catalog
