---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: config.porch.kpt.dev|PackageVariant|porch-system|mesh-headscale
    kpt.dev/package-layer: gitops
    kpt.dev/package-name: porch-resources
  name: mesh-headscale
  namespace: porch-system
spec:
  adoptionPolicy: adoptNone
  deletionPolicy: delete
  downstream:
    package: mesh/headscale
    repo: alcide-state
  labels:
    cluster-name: alcide
    nxmatic.dev/app: headscale
    nxmatic.dev/component: mesh
  packageContext:
    data:
      cluster-env: dave
      cluster-name: alcide
  pipeline:
    mutators:
      - configMap:
          cluster-lan-headscale-inetaddr: 192.168.1.65
          cluster-lan-lb-cidr: 192.168.1.64/27
          cluster-name: alcide
          cluster-vip-cidr: 10.80.15.0/24
          darwin-host: alcide
        image: ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.2
  upstream:
    package: mesh/headscale
    repo: alcide-catalog
