apiVersion: apps/v1
kind: DaemonSet
metadata: # kpt-merge: ${kube-vip-namespace}/kube-vip-ds
  name: kube-vip-ds
  namespace: ${kube-vip-namespace} # kpt-set: ${kube-vip-namespace}
  labels:
    app: kube-vip
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|DaemonSet|${kube-vip-namespace}|kube-vip-ds'
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      labels:
        name: kube-vip-ds
        app: kube-vip
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      containers:
      - name: kube-vip
        image: ghcr.io/kube-vip/kube-vip:v0.8.7 # kpt-set: ghcr.io/kube-vip/kube-vip:${kube-vip-version}
        imagePullPolicy: Always
        args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ${cluster-vip-interface} # kpt-set: ${cluster-vip-interface}
        - name: vip_cidr
          value: "32"
        - name: dns_mode
          value: "first"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: ${cluster-node-vip-inetaddr} # kpt-set: ${cluster-node-vip-inetaddr}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
