schema-version = "1.10.0"


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
pulumi.pkg-path = "pulumi-bin"
pulumictl.pkg-path = "pulumictl"
distrobuilder.pkg-path = "distrobuilder"
distrobuilder.systems = ["aarch64-linux"]
cdk8s-cli.pkg-path = "cdk8s-cli"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
  PULUMI_CONFIG_PASSPHRASE=''
  PULUMI_HOME='${XDG_STATE_HOME:-$HOME/.local/state}/pulumi'
  PULUMI_BACKEND_URL='file://${FLOX_ENV_PROJECT}/.pulumi-state'

# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = '''
  mkdir -p "${PULUMI_HOME}"
  mkdir -p "${FLOX_ENV_PROJECT}/.pulumi-state"
'''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
common = '''
  if command -v javac >/dev/null 2>&1; then
    export JAVA_HOME="$(dirname "$(dirname "$(command -v javac)")")"
  fi
'''
## Shell-specific customizations such as setting aliases go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ---------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## ------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Include ----------------------------------------------------------
## ... environments to create a composed environment
## ------------------------------------------------------------------
[include]
environments = [
  { dir = "../fleet/flox/git" },
  { dir = "../fleet/flox/jdk" },
  { dir = "../fleet/flox/k8s" },
  { dir = "../fleet/flox/pulumi" }
]


## Build and publish your own packages ------------------------------
##  $ flox build
##  $ flox publish
## ------------------------------------------------------------------
[build]
# [build.myproject]
# description = "The coolest project ever"
# version = "0.0.1"
# command = """
#   mkdir -p $out/bin
#   cargo build --release
#   cp target/release/myproject $out/bin/myproject
# """


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
# systems = [
#   "aarch64-darwin",
#   "aarch64-linux",
#   "x86_64-darwin",
#   "x86_64-linux",
# ]
# Uncomment to disable CUDA detection.
# cuda-detection = false
