apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: flox-runtime/flox-env
  name: flox-env
  namespace: flox-runtime
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|flox-runtime|flox-env'
data:
  FLOX_DISABLE_METRICS: "true"
  FLOX_NO_TELEMETRY: "1"
  FLOX_NONINTERACTIVE: "1"
