apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdns
spec:
  template:
    spec:
      dnsPolicy: Default
      containers:
        - name: kdns
          env: # {"$patch": "replace"}
            - name: KUBERNETES_SERVICE_HOST
              value: 10.80.8.10
            - name: KUBERNETES_SERVICE_PORT
              value: "6443"