---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    io.seedmatic.rke2lab/domain: mesh
    io.seedmatic.rke2lab/package: headplane
  name: headplane-secrets
  namespace: mesh-system
stringData:
  cookie_secret: 0123456789abcdef0123456789abcdef
type: Opaque
