// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class GetStorageBucketArgs extends com.pulumi.resources.InvokeArgs {

  public static final GetStorageBucketArgs Empty = new GetStorageBucketArgs();

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "location")
  private @Nullable Output<String> location;

  public Optional<Output<String>> location() {
    return Optional.ofNullable(this.location);
  }

  @Import(name = "name", required = true)
  private Output<String> name;

  public Output<String> name() {
    return this.name;
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "s3Url")
  private @Nullable Output<String> s3Url;

  public Optional<Output<String>> s3Url() {
    return Optional.ofNullable(this.s3Url);
  }

  @Import(name = "storagePool", required = true)
  private Output<String> storagePool;

  public Output<String> storagePool() {
    return this.storagePool;
  }

  @Import(name = "target")
  private @Nullable Output<String> target;

  public Optional<Output<String>> target() {
    return Optional.ofNullable(this.target);
  }

  private GetStorageBucketArgs() {}

  private GetStorageBucketArgs(GetStorageBucketArgs $) {
    this.description = $.description;
    this.location = $.location;
    this.name = $.name;
    this.project = $.project;
    this.remote = $.remote;
    this.s3Url = $.s3Url;
    this.storagePool = $.storagePool;
    this.target = $.target;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(GetStorageBucketArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private GetStorageBucketArgs $;

    public Builder() {
      $ = new GetStorageBucketArgs();
    }

    public Builder(GetStorageBucketArgs defaults) {
      $ = new GetStorageBucketArgs(Objects.requireNonNull(defaults));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    public Builder location(@Nullable Output<String> location) {
      $.location = location;
      return this;
    }

    public Builder location(String location) {
      return location(Output.of(location));
    }

    public Builder name(Output<String> name) {
      $.name = name;
      return this;
    }

    public Builder name(String name) {
      return name(Output.of(name));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public Builder s3Url(@Nullable Output<String> s3Url) {
      $.s3Url = s3Url;
      return this;
    }

    public Builder s3Url(String s3Url) {
      return s3Url(Output.of(s3Url));
    }

    public Builder storagePool(Output<String> storagePool) {
      $.storagePool = storagePool;
      return this;
    }

    public Builder storagePool(String storagePool) {
      return storagePool(Output.of(storagePool));
    }

    public Builder target(@Nullable Output<String> target) {
      $.target = target;
      return this;
    }

    public Builder target(String target) {
      return target(Output.of(target));
    }

    public GetStorageBucketArgs build() {
      if ($.name == null) {
        throw new MissingRequiredPropertyException("GetStorageBucketArgs", "name");
      }
      if ($.storagePool == null) {
        throw new MissingRequiredPropertyException("GetStorageBucketArgs", "storagePool");
      }
      return $;
    }
  }
}
