// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class ImageState extends com.pulumi.resources.ResourceArgs {

  public static final ImageState Empty = new ImageState();

  /** Image alias */
  @Import(name = "aliases")
  private @Nullable Output<List<ImageAliasArgs>> aliases;

  /**
   * @return Image alias
   */
  public Optional<Output<List<ImageAliasArgs>>> aliases() {
    return Optional.ofNullable(this.aliases);
  }

  @Import(name = "copiedAliases")
  private @Nullable Output<List<String>> copiedAliases;

  public Optional<Output<List<String>>> copiedAliases() {
    return Optional.ofNullable(this.copiedAliases);
  }

  @Import(name = "createdAt")
  private @Nullable Output<Double> createdAt;

  public Optional<Output<Double>> createdAt() {
    return Optional.ofNullable(this.createdAt);
  }

  @Import(name = "fingerprint")
  private @Nullable Output<String> fingerprint;

  public Optional<Output<String>> fingerprint() {
    return Optional.ofNullable(this.fingerprint);
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  @Import(name = "resourceId")
  private @Nullable Output<String> resourceId;

  public Optional<Output<String>> resourceId() {
    return Optional.ofNullable(this.resourceId);
  }

  @Import(name = "sourceFile")
  private @Nullable Output<ImageSourceFileArgs> sourceFile;

  public Optional<Output<ImageSourceFileArgs>> sourceFile() {
    return Optional.ofNullable(this.sourceFile);
  }

  @Import(name = "sourceImage")
  private @Nullable Output<ImageSourceImageArgs> sourceImage;

  public Optional<Output<ImageSourceImageArgs>> sourceImage() {
    return Optional.ofNullable(this.sourceImage);
  }

  @Import(name = "sourceInstance")
  private @Nullable Output<ImageSourceInstanceArgs> sourceInstance;

  public Optional<Output<ImageSourceInstanceArgs>> sourceInstance() {
    return Optional.ofNullable(this.sourceInstance);
  }

  private ImageState() {}

  private ImageState(ImageState $) {
    this.aliases = $.aliases;
    this.copiedAliases = $.copiedAliases;
    this.createdAt = $.createdAt;
    this.fingerprint = $.fingerprint;
    this.project = $.project;
    this.remote = $.remote;
    this.resourceId = $.resourceId;
    this.sourceFile = $.sourceFile;
    this.sourceImage = $.sourceImage;
    this.sourceInstance = $.sourceInstance;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(ImageState defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private ImageState $;

    public Builder() {
      $ = new ImageState();
    }

    public Builder(ImageState defaults) {
      $ = new ImageState(Objects.requireNonNull(defaults));
    }

    /**
     * @param aliases Image alias
     * @return builder
     */
    public Builder aliases(@Nullable Output<List<ImageAliasArgs>> aliases) {
      $.aliases = aliases;
      return this;
    }

    /**
     * @param aliases Image alias
     * @return builder
     */
    public Builder aliases(List<ImageAliasArgs> aliases) {
      return aliases(Output.of(aliases));
    }

    /**
     * @param aliases Image alias
     * @return builder
     */
    public Builder aliases(ImageAliasArgs... aliases) {
      return aliases(List.of(aliases));
    }

    public Builder copiedAliases(@Nullable Output<List<String>> copiedAliases) {
      $.copiedAliases = copiedAliases;
      return this;
    }

    public Builder copiedAliases(List<String> copiedAliases) {
      return copiedAliases(Output.of(copiedAliases));
    }

    public Builder copiedAliases(String... copiedAliases) {
      return copiedAliases(List.of(copiedAliases));
    }

    public Builder createdAt(@Nullable Output<Double> createdAt) {
      $.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(Double createdAt) {
      return createdAt(Output.of(createdAt));
    }

    public Builder fingerprint(@Nullable Output<String> fingerprint) {
      $.fingerprint = fingerprint;
      return this;
    }

    public Builder fingerprint(String fingerprint) {
      return fingerprint(Output.of(fingerprint));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public Builder resourceId(@Nullable Output<String> resourceId) {
      $.resourceId = resourceId;
      return this;
    }

    public Builder resourceId(String resourceId) {
      return resourceId(Output.of(resourceId));
    }

    public Builder sourceFile(@Nullable Output<ImageSourceFileArgs> sourceFile) {
      $.sourceFile = sourceFile;
      return this;
    }

    public Builder sourceFile(ImageSourceFileArgs sourceFile) {
      return sourceFile(Output.of(sourceFile));
    }

    public Builder sourceImage(@Nullable Output<ImageSourceImageArgs> sourceImage) {
      $.sourceImage = sourceImage;
      return this;
    }

    public Builder sourceImage(ImageSourceImageArgs sourceImage) {
      return sourceImage(Output.of(sourceImage));
    }

    public Builder sourceInstance(@Nullable Output<ImageSourceInstanceArgs> sourceInstance) {
      $.sourceInstance = sourceInstance;
      return this;
    }

    public Builder sourceInstance(ImageSourceInstanceArgs sourceInstance) {
      return sourceInstance(Output.of(sourceInstance));
    }

    public ImageState build() {
      return $;
    }
  }
}
