apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: ${target-namespace}/kdns
  name: kdns
  namespace: ${target-namespace} # kpt-set: ${target-namespace}
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|${target-namespace}|kdns'
spec:
  template:
    metadata:
      annotations:
        flox.dev/environment: "nxmatic/kdns" # kpt-set: ${kdns-flox-env}
    spec:
      runtimeClassName: flox
      containers:
        - name: kdns
          image: flox/empty:1.0.0
          command:
            - kdns
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /.config/flox
              name: flox-config
            - mountPath: /.cache/flox
              name: flox-cache
      volumes:
        - emptyDir: {}
          name: flox-config
        - emptyDir: {}
          name: flox-cache
