// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.incus.inputs.CertificateState;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type = "incus:index/certificate:Certificate")
public class Certificate extends com.pulumi.resources.CustomResource {
  @Export(
      name = "certificate",
      refs = {String.class},
      tree = "[0]")
  private Output<String> certificate;

  public Output<String> certificate() {
    return this.certificate;
  }

  @Export(
      name = "description",
      refs = {String.class},
      tree = "[0]")
  private Output<String> description;

  public Output<String> description() {
    return this.description;
  }

  @Export(
      name = "fingerprint",
      refs = {String.class},
      tree = "[0]")
  private Output<String> fingerprint;

  public Output<String> fingerprint() {
    return this.fingerprint;
  }

  @Export(
      name = "name",
      refs = {String.class},
      tree = "[0]")
  private Output<String> name;

  public Output<String> name() {
    return this.name;
  }

  @Export(
      name = "projects",
      refs = {List.class, String.class},
      tree = "[0,1]")
  private Output<List<String>> projects;

  public Output<List<String>> projects() {
    return this.projects;
  }

  @Export(
      name = "remote",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> remote;

  public Output<Optional<String>> remote() {
    return Codegen.optional(this.remote);
  }

  @Export(
      name = "restricted",
      refs = {Boolean.class},
      tree = "[0]")
  private Output<Boolean> restricted;

  public Output<Boolean> restricted() {
    return this.restricted;
  }

  @Export(
      name = "type",
      refs = {String.class},
      tree = "[0]")
  private Output<String> type;

  public Output<String> type() {
    return this.type;
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   */
  public Certificate(java.lang.String name) {
    this(name, CertificateArgs.Empty);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   */
  public Certificate(java.lang.String name, CertificateArgs args) {
    this(name, args, null);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param options A bag of options that control this resource's behavior.
   */
  public Certificate(
      java.lang.String name,
      CertificateArgs args,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/certificate:Certificate",
        name,
        makeArgs(args, options),
        makeResourceOptions(options, Codegen.empty()),
        false,
        Utilities.getPackageRef());
  }

  private Certificate(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable CertificateState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/certificate:Certificate",
        name,
        state,
        makeResourceOptions(options, id),
        false,
        Utilities.getPackageRef());
  }

  private static CertificateArgs makeArgs(
      CertificateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
    if (options != null && options.getUrn().isPresent()) {
      return null;
    }
    return args == null ? CertificateArgs.Empty : args;
  }

  private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(
      @Nullable com.pulumi.resources.CustomResourceOptions options,
      @Nullable Output<java.lang.String> id) {
    var defaultOptions =
        com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
    return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
  }

  /**
   * Get an existing Host resource's state with the given name, ID, and optional extra properties
   * used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state
   * @param options Optional settings to control the behavior of the CustomResource.
   */
  public static Certificate get(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable CertificateState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    return new Certificate(name, id, state, options);
  }
}
