// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterGroupMemberArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterGroupMemberArgs Empty = new ClusterGroupMemberArgs();

    @Import(name="clusterGroup", required=true)
    private Output<String> clusterGroup;

    public Output<String> clusterGroup() {
        return this.clusterGroup;
    }

    @Import(name="member", required=true)
    private Output<String> member;

    public Output<String> member() {
        return this.member;
    }

    @Import(name="remote")
    private @Nullable Output<String> remote;

    public Optional<Output<String>> remote() {
        return Optional.ofNullable(this.remote);
    }

    private ClusterGroupMemberArgs() {}

    private ClusterGroupMemberArgs(ClusterGroupMemberArgs $) {
        this.clusterGroup = $.clusterGroup;
        this.member = $.member;
        this.remote = $.remote;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterGroupMemberArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterGroupMemberArgs $;

        public Builder() {
            $ = new ClusterGroupMemberArgs();
        }

        public Builder(ClusterGroupMemberArgs defaults) {
            $ = new ClusterGroupMemberArgs(Objects.requireNonNull(defaults));
        }

        public Builder clusterGroup(Output<String> clusterGroup) {
            $.clusterGroup = clusterGroup;
            return this;
        }

        public Builder clusterGroup(String clusterGroup) {
            return clusterGroup(Output.of(clusterGroup));
        }

        public Builder member(Output<String> member) {
            $.member = member;
            return this;
        }

        public Builder member(String member) {
            return member(Output.of(member));
        }

        public Builder remote(@Nullable Output<String> remote) {
            $.remote = remote;
            return this;
        }

        public Builder remote(String remote) {
            return remote(Output.of(remote));
        }

        public ClusterGroupMemberArgs build() {
            if ($.clusterGroup == null) {
                throw new MissingRequiredPropertyException("ClusterGroupMemberArgs", "clusterGroup");
            }
            if ($.member == null) {
                throw new MissingRequiredPropertyException("ClusterGroupMemberArgs", "member");
            }
            return $;
        }
    }

}
