// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.incus.inputs.ImageState;
import com.pulumi.incus.outputs.ImageAlias;
import com.pulumi.incus.outputs.ImageSourceFile;
import com.pulumi.incus.outputs.ImageSourceImage;
import com.pulumi.incus.outputs.ImageSourceInstance;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type = "incus:index/image:Image")
public class Image extends com.pulumi.resources.CustomResource {
  /** Image alias */
  @Export(
      name = "aliases",
      refs = {List.class, ImageAlias.class},
      tree = "[0,1]")
  private Output</* @Nullable */ List<ImageAlias>> aliases;

  /**
   * @return Image alias
   */
  public Output<Optional<List<ImageAlias>>> aliases() {
    return Codegen.optional(this.aliases);
  }

  @Export(
      name = "copiedAliases",
      refs = {List.class, String.class},
      tree = "[0,1]")
  private Output<List<String>> copiedAliases;

  public Output<List<String>> copiedAliases() {
    return this.copiedAliases;
  }

  @Export(
      name = "createdAt",
      refs = {Double.class},
      tree = "[0]")
  private Output<Double> createdAt;

  public Output<Double> createdAt() {
    return this.createdAt;
  }

  @Export(
      name = "fingerprint",
      refs = {String.class},
      tree = "[0]")
  private Output<String> fingerprint;

  public Output<String> fingerprint() {
    return this.fingerprint;
  }

  @Export(
      name = "project",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> project;

  public Output<Optional<String>> project() {
    return Codegen.optional(this.project);
  }

  @Export(
      name = "remote",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> remote;

  public Output<Optional<String>> remote() {
    return Codegen.optional(this.remote);
  }

  @Export(
      name = "resourceId",
      refs = {String.class},
      tree = "[0]")
  private Output<String> resourceId;

  public Output<String> resourceId() {
    return this.resourceId;
  }

  @Export(
      name = "sourceFile",
      refs = {ImageSourceFile.class},
      tree = "[0]")
  private Output</* @Nullable */ ImageSourceFile> sourceFile;

  public Output<Optional<ImageSourceFile>> sourceFile() {
    return Codegen.optional(this.sourceFile);
  }

  @Export(
      name = "sourceImage",
      refs = {ImageSourceImage.class},
      tree = "[0]")
  private Output</* @Nullable */ ImageSourceImage> sourceImage;

  public Output<Optional<ImageSourceImage>> sourceImage() {
    return Codegen.optional(this.sourceImage);
  }

  @Export(
      name = "sourceInstance",
      refs = {ImageSourceInstance.class},
      tree = "[0]")
  private Output</* @Nullable */ ImageSourceInstance> sourceInstance;

  public Output<Optional<ImageSourceInstance>> sourceInstance() {
    return Codegen.optional(this.sourceInstance);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   */
  public Image(java.lang.String name) {
    this(name, ImageArgs.Empty);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   */
  public Image(java.lang.String name, @Nullable ImageArgs args) {
    this(name, args, null);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param options A bag of options that control this resource's behavior.
   */
  public Image(
      java.lang.String name,
      @Nullable ImageArgs args,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/image:Image",
        name,
        makeArgs(args, options),
        makeResourceOptions(options, Codegen.empty()),
        false,
        Utilities.getPackageRef());
  }

  private Image(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable ImageState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/image:Image",
        name,
        state,
        makeResourceOptions(options, id),
        false,
        Utilities.getPackageRef());
  }

  private static ImageArgs makeArgs(
      @Nullable ImageArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
    if (options != null && options.getUrn().isPresent()) {
      return null;
    }
    return args == null ? ImageArgs.Empty : args;
  }

  private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(
      @Nullable com.pulumi.resources.CustomResourceOptions options,
      @Nullable Output<java.lang.String> id) {
    var defaultOptions =
        com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
    return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
  }

  /**
   * Get an existing Host resource's state with the given name, ID, and optional extra properties
   * used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state
   * @param options Optional settings to control the behavior of the CustomResource.
   */
  public static Image get(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable ImageState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    return new Image(name, id, state, options);
  }
}
