// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.incus.InstanceSnapshotArgs;
import com.pulumi.incus.Utilities;
import com.pulumi.incus.inputs.InstanceSnapshotState;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="incus:index/instanceSnapshot:InstanceSnapshot")
public class InstanceSnapshot extends com.pulumi.resources.CustomResource {
    @Export(name="createdAt", refs={Double.class}, tree="[0]")
    private Output<Double> createdAt;

    public Output<Double> createdAt() {
        return this.createdAt;
    }
    @Export(name="instance", refs={String.class}, tree="[0]")
    private Output<String> instance;

    public Output<String> instance() {
        return this.instance;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="project", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> project;

    public Output<Optional<String>> project() {
        return Codegen.optional(this.project);
    }
    @Export(name="remote", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> remote;

    public Output<Optional<String>> remote() {
        return Codegen.optional(this.remote);
    }
    @Export(name="stateful", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> stateful;

    public Output<Boolean> stateful() {
        return this.stateful;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public InstanceSnapshot(java.lang.String name) {
        this(name, InstanceSnapshotArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public InstanceSnapshot(java.lang.String name, InstanceSnapshotArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public InstanceSnapshot(java.lang.String name, InstanceSnapshotArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("incus:index/instanceSnapshot:InstanceSnapshot", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private InstanceSnapshot(java.lang.String name, Output<java.lang.String> id, @Nullable InstanceSnapshotState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("incus:index/instanceSnapshot:InstanceSnapshot", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static InstanceSnapshotArgs makeArgs(InstanceSnapshotArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? InstanceSnapshotArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static InstanceSnapshot get(java.lang.String name, Output<java.lang.String> id, @Nullable InstanceSnapshotState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new InstanceSnapshot(name, id, state, options);
    }
}
