// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.incus.NetworkPeerArgs;
import com.pulumi.incus.Utilities;
import com.pulumi.incus.inputs.NetworkPeerState;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="incus:index/networkPeer:NetworkPeer")
public class NetworkPeer extends com.pulumi.resources.CustomResource {
    @Export(name="config", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output<Map<String,String>> config;

    public Output<Map<String,String>> config() {
        return this.config;
    }
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    public Output<String> description() {
        return this.description;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="network", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> network;

    public Output<Optional<String>> network() {
        return Codegen.optional(this.network);
    }
    @Export(name="project", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> project;

    public Output<Optional<String>> project() {
        return Codegen.optional(this.project);
    }
    @Export(name="remote", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> remote;

    public Output<Optional<String>> remote() {
        return Codegen.optional(this.remote);
    }
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    public Output<String> status() {
        return this.status;
    }
    @Export(name="targetIntegration", refs={String.class}, tree="[0]")
    private Output<String> targetIntegration;

    public Output<String> targetIntegration() {
        return this.targetIntegration;
    }
    @Export(name="targetNetwork", refs={String.class}, tree="[0]")
    private Output<String> targetNetwork;

    public Output<String> targetNetwork() {
        return this.targetNetwork;
    }
    @Export(name="targetProject", refs={String.class}, tree="[0]")
    private Output<String> targetProject;

    public Output<String> targetProject() {
        return this.targetProject;
    }
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NetworkPeer(java.lang.String name) {
        this(name, NetworkPeerArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NetworkPeer(java.lang.String name, @Nullable NetworkPeerArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NetworkPeer(java.lang.String name, @Nullable NetworkPeerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("incus:index/networkPeer:NetworkPeer", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private NetworkPeer(java.lang.String name, Output<java.lang.String> id, @Nullable NetworkPeerState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("incus:index/networkPeer:NetworkPeer", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static NetworkPeerArgs makeArgs(@Nullable NetworkPeerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NetworkPeerArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NetworkPeer get(java.lang.String name, Output<java.lang.String> id, @Nullable NetworkPeerState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NetworkPeer(name, id, state, options);
    }
}
