// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.incus.inputs.NetworkForwardPortArgs;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

public final class NetworkForwardArgs extends com.pulumi.resources.ResourceArgs {

  public static final NetworkForwardArgs Empty = new NetworkForwardArgs();

  @Import(name = "config")
  private @Nullable Output<Map<String, String>> config;

  public Optional<Output<Map<String, String>>> config() {
    return Optional.ofNullable(this.config);
  }

  @Import(name = "description")
  private @Nullable Output<String> description;

  public Optional<Output<String>> description() {
    return Optional.ofNullable(this.description);
  }

  @Import(name = "listenAddress", required = true)
  private Output<String> listenAddress;

  public Output<String> listenAddress() {
    return this.listenAddress;
  }

  @Import(name = "network", required = true)
  private Output<String> network;

  public Output<String> network() {
    return this.network;
  }

  @Import(name = "ports")
  private @Nullable Output<List<NetworkForwardPortArgs>> ports;

  public Optional<Output<List<NetworkForwardPortArgs>>> ports() {
    return Optional.ofNullable(this.ports);
  }

  @Import(name = "project")
  private @Nullable Output<String> project;

  public Optional<Output<String>> project() {
    return Optional.ofNullable(this.project);
  }

  @Import(name = "remote")
  private @Nullable Output<String> remote;

  public Optional<Output<String>> remote() {
    return Optional.ofNullable(this.remote);
  }

  private NetworkForwardArgs() {}

  private NetworkForwardArgs(NetworkForwardArgs $) {
    this.config = $.config;
    this.description = $.description;
    this.listenAddress = $.listenAddress;
    this.network = $.network;
    this.ports = $.ports;
    this.project = $.project;
    this.remote = $.remote;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Builder builder(NetworkForwardArgs defaults) {
    return new Builder(defaults);
  }

  public static final class Builder {
    private NetworkForwardArgs $;

    public Builder() {
      $ = new NetworkForwardArgs();
    }

    public Builder(NetworkForwardArgs defaults) {
      $ = new NetworkForwardArgs(Objects.requireNonNull(defaults));
    }

    public Builder config(@Nullable Output<Map<String, String>> config) {
      $.config = config;
      return this;
    }

    public Builder config(Map<String, String> config) {
      return config(Output.of(config));
    }

    public Builder description(@Nullable Output<String> description) {
      $.description = description;
      return this;
    }

    public Builder description(String description) {
      return description(Output.of(description));
    }

    public Builder listenAddress(Output<String> listenAddress) {
      $.listenAddress = listenAddress;
      return this;
    }

    public Builder listenAddress(String listenAddress) {
      return listenAddress(Output.of(listenAddress));
    }

    public Builder network(Output<String> network) {
      $.network = network;
      return this;
    }

    public Builder network(String network) {
      return network(Output.of(network));
    }

    public Builder ports(@Nullable Output<List<NetworkForwardPortArgs>> ports) {
      $.ports = ports;
      return this;
    }

    public Builder ports(List<NetworkForwardPortArgs> ports) {
      return ports(Output.of(ports));
    }

    public Builder ports(NetworkForwardPortArgs... ports) {
      return ports(List.of(ports));
    }

    public Builder project(@Nullable Output<String> project) {
      $.project = project;
      return this;
    }

    public Builder project(String project) {
      return project(Output.of(project));
    }

    public Builder remote(@Nullable Output<String> remote) {
      $.remote = remote;
      return this;
    }

    public Builder remote(String remote) {
      return remote(Output.of(remote));
    }

    public NetworkForwardArgs build() {
      if ($.listenAddress == null) {
        throw new MissingRequiredPropertyException("NetworkForwardArgs", "listenAddress");
      }
      if ($.network == null) {
        throw new MissingRequiredPropertyException("NetworkForwardArgs", "network");
      }
      return $;
    }
  }
}
