// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.incus;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.incus.inputs.StorageBucketKeyState;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type = "incus:index/storageBucketKey:StorageBucketKey")
public class StorageBucketKey extends com.pulumi.resources.CustomResource {
  @Export(
      name = "accessKey",
      refs = {String.class},
      tree = "[0]")
  private Output<String> accessKey;

  public Output<String> accessKey() {
    return this.accessKey;
  }

  @Export(
      name = "description",
      refs = {String.class},
      tree = "[0]")
  private Output<String> description;

  public Output<String> description() {
    return this.description;
  }

  @Export(
      name = "name",
      refs = {String.class},
      tree = "[0]")
  private Output<String> name;

  public Output<String> name() {
    return this.name;
  }

  @Export(
      name = "pool",
      refs = {String.class},
      tree = "[0]")
  private Output<String> pool;

  public Output<String> pool() {
    return this.pool;
  }

  @Export(
      name = "project",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> project;

  public Output<Optional<String>> project() {
    return Codegen.optional(this.project);
  }

  @Export(
      name = "remote",
      refs = {String.class},
      tree = "[0]")
  private Output</* @Nullable */ String> remote;

  public Output<Optional<String>> remote() {
    return Codegen.optional(this.remote);
  }

  @Export(
      name = "role",
      refs = {String.class},
      tree = "[0]")
  private Output<String> role;

  public Output<String> role() {
    return this.role;
  }

  @Export(
      name = "secretKey",
      refs = {String.class},
      tree = "[0]")
  private Output<String> secretKey;

  public Output<String> secretKey() {
    return this.secretKey;
  }

  @Export(
      name = "storageBucket",
      refs = {String.class},
      tree = "[0]")
  private Output<String> storageBucket;

  public Output<String> storageBucket() {
    return this.storageBucket;
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   */
  public StorageBucketKey(java.lang.String name) {
    this(name, StorageBucketKeyArgs.Empty);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   */
  public StorageBucketKey(java.lang.String name, StorageBucketKeyArgs args) {
    this(name, args, null);
  }

  /**
   * @param name The _unique_ name of the resulting resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param options A bag of options that control this resource's behavior.
   */
  public StorageBucketKey(
      java.lang.String name,
      StorageBucketKeyArgs args,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/storageBucketKey:StorageBucketKey",
        name,
        makeArgs(args, options),
        makeResourceOptions(options, Codegen.empty()),
        false,
        Utilities.getPackageRef());
  }

  private StorageBucketKey(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable StorageBucketKeyState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    super(
        "incus:index/storageBucketKey:StorageBucketKey",
        name,
        state,
        makeResourceOptions(options, id),
        false,
        Utilities.getPackageRef());
  }

  private static StorageBucketKeyArgs makeArgs(
      StorageBucketKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
    if (options != null && options.getUrn().isPresent()) {
      return null;
    }
    return args == null ? StorageBucketKeyArgs.Empty : args;
  }

  private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(
      @Nullable com.pulumi.resources.CustomResourceOptions options,
      @Nullable Output<java.lang.String> id) {
    var defaultOptions =
        com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of("accessKey", "secretKey"))
            .build();
    return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
  }

  /**
   * Get an existing Host resource's state with the given name, ID, and optional extra properties
   * used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state
   * @param options Optional settings to control the behavior of the CustomResource.
   */
  public static StorageBucketKey get(
      java.lang.String name,
      Output<java.lang.String> id,
      @Nullable StorageBucketKeyState state,
      @Nullable com.pulumi.resources.CustomResourceOptions options) {
    return new StorageBucketKey(name, id, state, options);
  }
}
