<?xml version="1.0" encoding="UTF-8"?>
<!-- @codebase -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.nxmatic.rke2lab</groupId>
    <artifactId>parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>seed-master</artifactId>
  <name>seed-master</name>

  <properties>
    <rk2lab.manifests.unpack.skip>false</rk2lab.manifests.unpack.skip>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.nxmatic.rke2lab</groupId>
        <artifactId>bom</artifactId>
        <version>${project.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.pulumi</groupId>
      <artifactId>pulumi</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-common-protos</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty</artifactId>
    </dependency>
    <dependency>
      <groupId>io.nxmatic.rke2lab.sdks</groupId>
      <artifactId>incus</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.nxmatic.rke2lab</groupId>
      <artifactId>manifests</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.nxmatic.rke2lab</groupId>
      <artifactId>netplan</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.nxmatic.rke2lab</groupId>
      <artifactId>systemd-contract</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.nxmatic</groupId>
      <artifactId>java-bbox-api-client</artifactId>
      <version>0.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-yaml</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jgit</groupId>
      <artifactId>org.eclipse.jgit</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.thjomnx</groupId>
      <artifactId>java-systemd</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.hypfvieh</groupId>
      <artifactId>dbus-java-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.hypfvieh</groupId>
      <artifactId>dbus-java-transport-tcp</artifactId>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>${project.basedir}/src/main/resources</directory>
      </resource>
      <resource>
        <directory>${project.build.directory}/generated-resources</directory>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>clean-unpacked-manifests-generated-resources</id>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <target>
                <delete dir="${project.build.directory}/generated-resources/META-INF/io.nxmatic/rk2lab/controlplane/incus/manifests" quiet="true"/>
                <delete dir="${project.build.directory}/classes/META-INF/io.nxmatic/rk2lab/controlplane/incus/manifests" quiet="true"/>
              </target>
            </configuration>
          </execution>
          <execution>
            <id>copy-incus-assets-into-generated-resources</id>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <target>
                <mkdir dir="${project.build.directory}/generated-resources/META-INF/io.nxmatic/rk2lab/controlplane/incus/assets"/>
                <copy overwrite="true" todir="${project.build.directory}/generated-resources/META-INF/io.nxmatic/rk2lab/controlplane/incus/assets">
                  <fileset dir="${maven.multiModuleProjectDirectory}/assets/incus" erroronmissingdir="false"/>
                </copy>
                <mkdir dir="${project.build.directory}/generated-resources/META-INF/io.nxmatic/rk2lab/controlplane/incus"/>
                <copy overwrite="true" todir="${project.build.directory}/generated-resources/META-INF/io.nxmatic/rk2lab/controlplane/incus">
                  <fileset dir="${project.basedir}/src/main/resources/incus"/>
                </copy>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>shade</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <shadedArtifactAttached>true</shadedArtifactAttached>
              <shadedClassifierName>exec</shadedClassifierName>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>io.nxmatic.rk2lab.controlplane.Main</mainClass>
                </transformer>
              </transformers>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/MANIFEST.MF</exclude>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/SIG-*</exclude>
                    <exclude>META-INF/LICENSE*</exclude>
                    <exclude>META-INF/NOTICE*</exclude>
                    <exclude>module-info.class</exclude>
                    <exclude>META-INF/versions/*/module-info.class</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <configuration>
          <mainClass>io.nxmatic.rk2lab.controlplane.Main</mainClass>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.8.1</version>
        <executions>
          <execution>
            <id>unpack-manifests-bundle</id>
            <goals>
              <goal>unpack</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <skip>${rk2lab.manifests.unpack.skip}</skip>
              <artifactItems>
                <artifactItem>
                  <groupId>io.nxmatic.rke2lab</groupId>
                  <artifactId>manifests</artifactId>
                  <version>${rke2lab.version}</version>
                  <classifier>manifests-d</classifier>
                  <type>zip</type>
                  <outputDirectory>${project.build.directory}/generated-resources/META-INF/io.nxmatic/rk2lab/controlplane/incus/manifests</outputDirectory>
                  <overWrite>true</overWrite>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>m2e</id>
      <activation>
        <property>
          <name>m2e.version</name>
        </property>
      </activation>
      <properties>
        <rk2lab.manifests.unpack.skip>true</rk2lab.manifests.unpack.skip>
      </properties>
    </profile>
  </profiles>
</project>
