apiVersion: v1
kind: Service
metadata:
  name: headplane
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
  labels:
    app: headplane
    io.cilium/lb-ipam-pool: lan
  annotations:
    io.cilium/lb-ipam-ips: ${cluster-lan-headplane-inetaddr} # kpt-set: ${cluster-lan-headplane-inetaddr}
spec:
  type: LoadBalancer
  selector:
    app: headplane
  ports:
    - name: http
      port: 3000
      targetPort: http
