apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headplane
  namespace: ${headscale-namespace} # kpt-set: ${headscale-namespace}
  annotations:
    kubernetes.io/ingress.class: ${headplane-ingress-class} # kpt-set: ${headplane-ingress-class}
  io.cilium/lb-ipam-ips: ${cluster-lan-headplane-inetaddr} # kpt-set: ${cluster-lan-headplane-inetaddr}
    kdns.lab42/enabled: "true"
    kdns.lab42/hostname: ${headplane-ingress-host} # kpt-set: ${headplane-ingress-host}
spec:
  ingressClassName: ${headplane-ingress-class} # kpt-set: ${headplane-ingress-class}
  rules:
    - host: ${headplane-ingress-host} # kpt-set: ${headplane-ingress-host}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headplane
                port:
                  number: 3000
